INSERT INTO `projeto_pwe`.`sinergia`
(`NOME`,
`FOTO`,
`DESCRIP`,
`MARCA_DESCRIP`,
`MARCA`,
`QTD_MK1`,
`QTD_MK2`,
`QTD_MK3`,
`QTD_MK4`,
`TIPO`)
VALUES
('Adepto',
'adepto.svg',
'Adeptos acalmam o fluxo da bvatalha, reduzindo a velocidade de ataque de seus inimigos em 50% durante alguns segundos no começo do combate.',
'2 - 2 Segundos; 3 - 3.5 Segundos; 4 - 6 Segundos',
3,
2,
3,
4,
NULL,
'C'),
('Assassino',
'assassino.svg',
'Antes do começo do combate, assassinos saltam para a linha de trás do inimigo. As habilidades de assassinos podem acertar criticamente, além de possuírem um bônus de chance de acerto crítico e dano crítico.',
'2 - 10% de chance de acerto crítico e 30% de dano crítico; 4 - 25% de chance de acerto crítico e 60% de dano crítico; 6 - 40% de chance de acerto crítico e 90% de dano crítico',
3,
2,
4,
6,
NULL,
'C'),
('Atirador',
'atirador.svg',
'Ataques e habilidades de atiradores ricocheteiam nos inimigos próximos causando dano reduzido.',
'2 - 1 ricochete com 55% de dano reduzido; 4 - 2 ricochetes com 50% de dano reduzido; 6 - 3 ricochetes com 45% de dano reduzido',
3,
2,
4,
6,
NULL,
'C'),
('Atormentado',
'atormentado.svg',
'Após participar de 3 combates, atormentados recebem a opção de se transformarem.',
'1 - Está atormentado',
1,
1,
NULL,
NULL,
NULL,
'O'),
('Caçador',
'cacador.svg',
'A cada x sengudos, todos os caçadores atacarão o inimigo com a vida mais baixa, causando dano aumentado.',
'2 - 125% de dano aumentado a cada 3.5 segundos; 3 - 150% de dano aumentado a cada 3 segundos; 4 - 175% de dano aumentado a cada 2.5 segundos; 5 - 200% de dano aumentado a cada 2 segundos',
4,
2,
3,
4,
5,
'C'),
('Crepúsculo',
'crepusculo.svg',
'Campeões do crepúsculo aumentam o poder de habilidade de todos os aliados.',
'2 - Todos os aliados ganham +20% de poder de habilidade; 4 - Campeões do crpúsculo ganham +50% de poder de habilidade; 6 - +40% de poder de habilidade para todos e +70% para campeões do crepúsculo',
3,
2,
4,
6,
NULL,
'O'),
('Cultista',
'cultista.svg',
'Assim que a vida da equipe é redduzida à menos de 50%, Galio é invocado, batendo no maior acúmulo de inimigos e arremessando-os ao ar. A vida e o dano de Galio escala com o nível de estrelas de todos os cultistas.',
'3 - Galio Tirano; 6 - Galio Senhor Demoníaco; 9 - Galio Soberano Infernal',
3,
3,
6,
9,
NULL,
'O'),
('Divino',
'divino.svg',
'Ao atacar 6 vezes ou ter a vida reduzida abaixo de 50%, divindades removem todos os controles de grupo e ascendem, tomando dano reduzido em 50% e causando um bônus de 45% de dano verdadeiro pela duração da ascenção.',
'2 - 3 segundos de ascenção; 4 - 6 segundos de ascenção; 6 - 9 segundos de ascenção; 8 - 15 segundos de ascenção',
4,
2,
4,
6,
8,
'O'),
('Duelista',
'duelista.svg',
'Duelistas movem-se mais rápido. Os ataques de duelistas concedem um bônus de velocidade de ataque, acumulando até 8 vezes.',
'2 - +12% de velocidade de ataque por acúmulo; 4 - +20% de velocidade de ataque por acúmulo; 6 - +35% de velocidade de ataque por acúmulo; 8 - +60% de velocidade de ataque por acúmulo',
4,
2,
4,
6,
8,
'C'),
('Espírito',
'espirito.svg',
'A primeira vez que um espírito conjurar sua habilidade, todos os aliados ganharão velocidade de ataque proporcional ao custo de mana da habilidade.',
'2 - 35% do custo de mana; 4 - 70% do custo de mana',
2,
2,
4,
NULL,
NULL,
'O'),
('Exilado',
'exilado.svg',
'Se, no começo do combate, um campeão exilado não possuir aliados em sua volta, ele receberá alguns bônus.',
'1 - Um escudo igual à 50% de suas vidas máximas; 2 - 80% de roubo de vida',
2,
1,
2,
NULL,
NULL,
'O'),
('Fortuna',
'fortuna.svg',
'Ganhar uma batalha contra um jogador concederá espólios bônus. Quanto maior o tempo sem uma vitória, maior a quantidade e qualidade dos espólios.',
'3 - O efeito é ativado; 6 - Vitórias concedem um espólio extra com conteúdo raro',
2,
3,
6,
NULL,
NULL,
'O'),
('Iluminado',
'iluminado.svg',
'Iluminados geram uma maior quantidade de mana.',
'2 - 40% mais mana; 4 - 70% mais mana; 6 - 100% mais mana',
3,
2,
4,
6,
NULL,
'O'),
('Imperador',
'imperador.svg',
'O imperador surge com 2 unidades adicionais que podem ser movidaes separadamente. Estes escudeiros não se movem, nem atacam e morrem quando o imperador morre.',
'1 - Imperador está presente',
1,
1,
NULL,
NULL,
NULL,
'C'),
('Lunar',
'lunar.svg',
'No início de um combate, o aliado lunar com o menor nível de estrela recebe uma estrela a mais até o fim do combate. (Em caso de empate, o lunar com maior quantidade de itens é escolhido.)',
'3 - O efeito é ativado; 5 - Concede mais uma estrela à 2 lunares',
2,
3,
5,
NULL,
NULL,
'O'),
('Lutador',
'lutador.svg',
'Lutadores possuem vida máxima aumentada.',
'2 - +400 de vida; 4 - +800 de vida; 6 - +1200 de vida; 8 - +1800 de vida',
4,
2,
4,
6,
8,
'C'),
('Mago',
'mago.svg',
'Magos usam suas habilidades duas vezes e possuem um poder de habilidade modificado.',
'3 - 80% de seu poder de habilidade total; 6 - 120% de seu poder de habilidade total; 9 - 180% de seu poder de habilidade total',
3,
3,
6,
9,
NULL,
'C'),
('Mestre da Guerra',
'mestre_da_guerra.svg',
'Mestres da guerra possuem um bônus de vida e poder de habilidade. Cada batalha vitoriosa à qual participaram aumenta esse bônus em 10%, acumulando até 5 vezes.',
'3 - +200 de vida e +20 de poder de habilidade; 6 - +450 de vida e +40 de poder de habilidade; 9 - +700 de vida e +70 de poder de habilidade',
3,
3,
6,
9,
NULL,
'O'),
('Místico',
'mistico.svg',
'Todos os aliados possuem resistência mágica aumentada.',
'2 - +40 de resistência mágica; 4 - +100 de resistência mágica; 6 - +200 de resistência mágica',
3,
2,
4,
6,
NULL,
'C'),
('Ninja',
'ninja.svg',
'Ninjas recebem um bônus de dano e poder de habilidade. Este efeito só é concebido com, exatamente, 1 ou 4 ninjas.',
'1 - +50 de dano e poder de habilidade; 4 - +140 de dano e poder de habilidade',
2,
1,
4,
NULL,
NULL,
'O'),
('O chefe',
'o_chefe.svg',
'Quando a vida do chefe for reduzida, pela primeira vez, abaixo de 40%, ele se retira do combate para fazer abdominais. Cada abdominal recupera 15% de sua vida e o concede 40% de velocidade de movimento e ataque. Se ele recuperar a vida por completo, ele retorna ao combate animado, convertendo todo o seu dano em dano verdadeiro. Se todos os seus aliados morrerem, ele irá voltar para o combate imediatamente.',
'1 - O chefe está aqui',
1,
1,
NULL,
NULL,
NULL,
'O'),
('Ofuscante',
'ofuscante.svg',
'As habilidades dos ofuscantes reduzem o dano de ataque de seus alvos durante 8 segundos.',
'2 - -40% de dano de ataque; 4 - -80% de dano de ataque',
2,
2,
4,
NULL,
NULL,
'C'),
('Patrono',
'patrono.svg',
'No começo do combate, patronos concedem a si mesmos e aos aliados próximos um escudo que dura alguns segundos. Os escudos são 50% mais fortes nos patronos.',
'2 - 150 de escudo por 8 segundos; 4 - 225 de escudo por 10 segundos; 6 - 350 de escudo por 12 segundos',
3,
2,
4,
6,
NULL,
'C'),
('Sabugueiro',
'sabugueiro.svg',
'A cada 2 segundos, aliados sabugueiros crescem, ganhando status bônus. Este efeito acumula até 5 vezes.',
'3 - +20 de armadura e resistência mágica e +5 de dano e podeer de habilidade; 6 - +30 de armadura e resistência mágica e +10 de dano e podeer de habilidade; 9 - +40 de armadura e resistência mágica e +20 de dano e podeer de habilidade',
3,
3,
6,
9,
NULL,
'O'),
('Vanguarda',
'vanguarda.svg',
'Vanguardas recebem um bônus de armadura.',
'2 - +120 de armadura; 4 - +300 de armadura; 6 - +750 de armaduras; 8 - +2000 de armadura',
4,
2,
4,
6,
8,
'C'),
('Vulto',
'vulto.svg',
'No começo do combate, vultos teleportam para a linha de trás do inimigo. A cada 3 ataques, vultos mergulham nas sombras, tornando-se invisíveis e fazendo com que seu próximo ataque cause dano mágico adicional.',
'2 - +125 de dano mágico; 3 - +400 de dano mágico; 4 - +750 de dano mágico',
3,
2,
3,
4,
NULL,
'C');