INSERT INTO `projeto_pwe`.`campeao`
(`NOME`,
`FOTO`,
`HABILIDADE`,
`HABILIDADE_FOTO`,
`HABILIDADE_DESCRIP`,
`HABILIDADE_NVL`,
`CUSTO`)
VALUES
('Aatrox',
'Aatrox.png',
'Correntes Infernais',
'aatrox-correntes-infernais.png',
'Depois de um breve momento, Aatrox puxa para si alguns dos inimigos mais distantes e depois golpeia o chão, causando dano mágico aos inimigos adjacentes.',
'Inimigos puxados: 2/2/5; Dano causado: 250/450/1250',
4),
('Ahri',
'Ahri.png',
'Bomba Espiritual',
'ahri-bomba-espiritual.png',
'Ahri canaliza seu poder, invocando uma grande bomba de energia espiritual. Após 1.5 segundos, ela arremessa-a em seu alvo, causando dano à todos os inimigos em até 2 hexes de distância. Se a canalização de Ahri for interrompida, ela lançará a bomba mais cedo, com área de impacto menor.',
'Dano causado: 500/700/3000',
4),
('Akali',
'Akali.png',
'Golpe dos Cinco Pontos',
'akali-golpe-dos-cinco-pontos.png',
'Akali arremessa kunais no seu alvo, causando dano mágico.',
'Dano causado: 175/250/400',
3),
('Annie',
'Annie.png',
'Escudo Fundido',
'annie-escudo-fundido.png',
'Annie lança um cone de chamas, causando dano mágico à inimigos em sua frente, além de gerar um escudo para si que dura alguns segundos.',
'Dano causado: 250/350/450; Quantidade de escudo: 500/700/900',
2),
('Aphelios',
'Aphelios.png',
'Torre de Sentinela',
'aphelios-torre-de-sentinela.png',
'Aphelios invoca uma sentinela por alguns segundos. Uma extensão de sua vontade, a sentinela conta como o próprio Aphelios ao atirar e causar dano e morre quando ele morre.',
'Duração da sentinela: 7/8/9/11',
2),
('Ashe',
'Ashe.png',
'Foco do Caçador',
'ashe-foco-do-cacador.png',
'Ashe ganha velocidade de ataque durante 5 segundos e o ataque básico dela se torna em uma rajada de flechas que causa 45% de seu dano físico.',
'Velocidade de ataque: 45/65/300%',
4),
('Azir',
'Azir.png',
'Decreto do Imperador',
'azir-decreto-do-imperador.png',
'Azir comanda o avanço de uma parede de soldados, causando dano e desacelerando os inimigos por 4 segundos. Inimigos próximos de Azir são arremessados para trás, inimigos distântes são arremessados para cima.',
'Dano causado: 200/350/8888',
5),
('Cassiopeia',
'Cassiopeia.png',
'Olhar Petrificador',
'cassiopeia-olhar-petrificador.png',
'Cassiopeia libera um cone de energia mágia na direção de seu alvo, causando dano mágico à todos os alvos atingidos, petrificando-os por alguns segundos e fazendo com que eles recebam 20% de dano aumentado, enquanto petrificados.',
'Dano causado: 275/400/2000; Duração do atordoamento: 2.5/3/5',
4),
('Diana',
'Diana.png',
'Cascata Lívida',
'diana-cascata-livida.png',
'Diana se protege com um escudo durante 4 segundos e invoca orbes lunares para orbitarem ao seu redor. Estes orbes explodem, causando dano mágico, ao entrar em contato com um inimigo, recriando seu escudo quando o último orbe explode.',
'Quantidade de escudo: 200/300/400/500; Quantidade de orbes: 4/5/6/8; Dano causado: 70/80/90/100',
1),
('Elise',
'Elise.png',
'Forma dee Aranha',
'elise-forma-de-aranha.png',
'Elise se transforma em uma aranha, ganhando uma porcentagem de sua vida máxima e fazendo com que seus ataques recuperem vida.',
'Quantidade de vida: 35/40/45%; Vida recuperada: 40/80/160',
1),
('Evelynn',
'Evelynn.png',
'Última Carícia',
'evelynn-ultima-caricia.png',
'Evelynn causa dano mágico à, no máximo, 3 inimigos próximos e então teleporta pra longe. O dano é aumentado em 250% contra alvos com menos da metade da vida.',
'Dano causado: 350/600/1500',
3),
('Ezreal',
'Ezreal.png',
'Barragem Incendiária',
'ezreal-barragem-incendiaria.png',
'Ezreal atira uma barragem contra o inimigo com maior velocidade de ataque, que cura os aliados por qual passa, concedendo-os +50% de velocidade de ataque por 5 segundos, e causa dano aos inimigos, reduzindo a velocidade de ataque dos mesmos em 50% por 5 segundos.',
'Quantidade de cura: 250/450/9999; Dano causado: 250/450/9999',
5),
('Fiora',
'Fiora.png',
'Ripostar',
'fiora-ripostar.png',
'Fiora adota uma postura defensiva por 1.5 segundos, tornando-se immune à dano e efeitos de habilidades inimigas. Ao sair da postura, ela riposta, causando dano mágico à um inimigo próximo e atordoando-o por alguns segundos.',
'Dano causado: 250/400/600; Tempo de atordoamento: 1.5/2/3',
1),
('Garen',
'Garen.png',
'Julgamento',
'garen-julgamento.png',
'Garen gira sua espada durante 4 segundos, reduzindo o dano mágico recebido em 80% e causando dano mágico aos inimigos próximos no decorrer da duração.',
'Dano causado: 450/675/1125',
1),
('Hecarim',
'Hecarim.png',
'Espírito da Vida',
'hecarim-espirito-da-vida.png',
'Hecarim cria, em torno de si, uma aura que dura 3 segundos. Inimigos dentro da aura tomam dano mágico e curam Hecarim no decorrer da duração.',
'Dano causado: 250/400/600; Quantidade de cura: 250/400/600',
2),
('Irelia',
'Irelia.png',
'Tempestade de Lâminas',
'irelia-tempestade-de-laminas.png',
'Irelia lança uma barragem de lâminas em sua frente, causando dano mágico e aplicando efeitos de ataque básico. Inimigos atingidos são desarmados por alguns segundos.',
'Dano causado: 200/300/600; Duração do desarme: 2.5/3/3.5',
3),
('Janna',
'Janna.png',
'Olho da Tempestade',
'janna-olho-da-tempestade.png',
'Janna concede um escudo à alguns dos aliados com menor vida por 4 segundos. Aliados com  escudo recebem um aumento de dano no decorrer da duração do mesmo.',
'Quantidade de aliados: 2/3/4; Quantidade de escudo: 250/300/400; Aumento de dano: 20/30/60',
2),
('Jarvan IV',
'JarvanIV.png',
'Ataque do Dragão',
'jarvan-iv-ataque-do-dragao.png',
'Jarvan atinge o inimigo mais distânte dentro de 3 hexes com sua lança e se puxa em sua direção, causando dano mágico às unidades por quais ele passa e lançando-as ao ar por 1 segundo.',
'Dano causado: 175/250/750',
2),
('Jax',
'Jax.png',
'Contra Ataque',
'jax-contra-ataque.png',
'Jax desvia de todos os ataques durante 2 segundos, então ataca todos as unidades próximas, causando dano mágico e atordoando-as durante 1.5 segundos.',
'Dano causado: 150/250/450',
2),
('Jhin',
'Jhin.png',
'Sussurro',
'jhin-sussurro.png',
'Passiva: Jhin converte cada 1% de sua velocidade de ataque bônus em 0.8 dano de ataque. A velocidade de ataque base de Jhin escala com seu nível de estrela. Todo 4º tiro de Jhin causa dano extra.',
'Dano extra: 444/500/1234%; Velocidade de ataque base: 0.85/0.9/1.2',
4),
('Jinx',
'Jinx.png',
'Fishbones',
'jinx-fishbones.png',
'Jinx atira um foguete, atordoando e causando dano ao alvo e à todas as unidades dentro de 1 hex.',
'Dano causado: 150/250/450; Duração do atordoamento: 1.5/2/2.5',
3),
('Kalista',
'Kalista.png',
'Lacerar',
'kalista-lacerar.png',
'Passiva: As lanças de kalista permanecem em seu alvo, cada uma capaz de causar uma porcentagem da vida máxima do mesmo em dano mágico ao ser removida. Kalista irá arrancar as lanças quando isto ocasionar na morte de seu alvo.',
'Dano da lança: 4/6/9%;',
3),
('Katarina',
'Katarina.png',
'Lótus Mortal',
'katarina-lotus-mortal.png',
'Katarina gira por 2.5 segundos, arremessando facas em alguns alvos próximos, causando dano mágico e reduzindo a cura dos mesmos em 50% por 5 segundos.',
'Inimigos atingidos: 4/6/8; Dano causado: 750/900/1600',
3),
('Kayn',
'Kayn.png',
'Ceifador',
'kayn-ceifador.png',
'Kayn avança na direção de um grupo de inimigos antes de golpear em um círculo em sua volta, causando dano mágico e aumentando o custo da habilidade de seus alvos em 33%. Se o golpe atingir apenas 1 alvo, Kayn usará a habilidade novamente.; Transformação Darkin: Kayn se cura em 50% de seu dano causado.; Transformação Shadow: Ceifador causa 50% mais dano durante os primeiros 10 segundos de combate.',
'Dano causado: 375/575/6666',
5),
('Kennen',
'Kennen.png',
'Turbilhão Cortante',
'kennen-turbilhao-cortante.png',
'Kennen invoca uma tempestade em sua volta, lançando relâmpagos à cada 0.5 segundos em todos os inimigos na área. Cada inimigo atingido por 3 relâmpagos é atordoado por 1.5 segundos.',
'Dano causado: 300/450/1200',
3),
('Kindred',
'Kindred.png',
'Dança do Pavor',
'kindred-danca-do-pavor.png',
'O lobo morde o alvo de Kindred, causando dano mágico e reduzindo a cura do mesmo em 80% por 5 segundos, enquanto isso, a ovelha salta para longe de seu alvo.',
'Dano causado: 450/650/1000',
3),
('Lee Sin',
'LeeSin.png',
'Punho Divino',
'lee-sin-punho-divino.png',
'Lee Sin soca seu alvo, lançando-o para a borda do campo de batalha e atordoando-o. Cada inimigo com qual o alvo colidir durante o empurrão receberá metade do dano causado e será atordoado por 1 segundo. Se o alvo ainda permanecer vivo, Lee Sin avançará até ele.; Se o alvo já estiver na borda do campo de batalha, Lee Sin o arremessará para fora, removendo-o do combate. Se Lee Sin possuir 3 níveis de estrela, ele executará um chute ao redor de seu alvo que arremessará todos os inimigos em volta para fora do campo de batalha, independente de suas posições.',
'Dano causado: 250/450/1000; Duração do atordoamento: 2/3/10',
5),
('Lillia',
'Lillia.png',
'Cantiga de Ninar',
'lillia-cantiga-de-ninar.png',
'Lillia conjura uma canção de ninar mágica, causando alguns dos inimigos com maior quantidade de vida atual a dormir por alguns segundos. Inimigos irão acordar ao receberem uma determinada quantidade de dano enquanto desacordados, recebendo um dano extra ao acordar.',
'Inimigos atingidos: 2/3/10; Dano ao acordar: 500/750/5000; Duração do sono: 3/4/8',
5),
('Lissandra',
'Lissandra.png',
'1000 Adagas',
'lissandra-1000-adagas.png',
'Lissandra arremessa uma adaga contra o inimigo com maior dano de ataque, que explode em 1000 outras adagas ao atingir um inimigo ou alcançar seu destino. Ambos, a adaga inicial e a explosão de adagas, causam dano mágico aos inimigos atingidos.',
'Dano da adaga: 350/450/550/750; Dano da explosão: 175/225/300/450',
1),
('Lulu',
'Lulu.png',
'Crescimento Virente',
'lulu-crescimento-virente.png',
'Lulu torna um aliado com pouca vida em um gigante, concendendo-o vida bônus e lançando ao ar inimigos próximos durante 1 segundo.',
'Vida bônus: 400/600/950',
2),
('Lux',
'Lux.png',
'Ligação da Luz',
'lux-ligacao-da-luz.png',
'Lux atira uma esfera de luz contra o inimigo mais distânte. Inimigos na tragetória da esfera recebem dano mágico e são atordoados por algusn segundos.',
'Dano causado: 300/400/700; Duração do atordoamento: 1.5/2/3',
3),
('Maokai',
'Maokai.png',
'Esmagamento Espinhoso',
'maokai-esmagamento-espinhoso.png',
'Maokai esmaga os inimigos em sua frente, causando dano mágico e reduzindo sua velocidade de ataque em 50% por 3 segundos.',
'Dano causado: 225/350/550',
1),
('Morgana',
'Morgana.png',
'Solo Sagrado',
'morgana-solo-sagrado.png',
'Morgana santifica o chão embaixo de seu alvo, causando dano mágico nos inimigos dentro da área durante 5 segundos e reduzindo suas resistências mágicas em 40% enquanto estiverem dentro. Morgana se cura em uma porcentagem do dano causado.',
'Dano causado: 250/400/2000; Vida recuperada: 20/25/30%',
4),
('Nami',
'Nami.png',
'Prisão Aquática',
'nami-prisao-aquatica.png',
'Nami aprisiona o inimigo mais próximo em uma bolha, causando dano mágico e os atordoando por alguns segundos.',
'Dano causado: 225/325/450; Duração do atordoamento: 2.5/3/4',
1),
('Nidalee',
'Nidalee.png',
'Arremessar Lança',
'nidalee-arremessar-lanca.png',
'Nidalee arremessa sua lança no inimigo mais distante, causando dano mágico. O dano é aumentado em 20% para cada hex de distância.',
'Dano causado: 225/350/600',
1),
('Nunu',
'Nunu.png',
'Consumir',
'nunu-consumir.png',
'Willump morde seu alvo, causando dano mágico. Se o alvo possuir menos vida que Willump antes da mordida, esta causará 50% a mais de dano e causará dano verdadeiro em vez de mágico.',
'Dano causado: 450/650/1800',
3),
('Pyke',
'Pyke.png',
'Ressaca Espectral',
'pyke-ressaca-espectral.png',
'Pyke avança para as costas do inimigo mais distânte, criando uma sombra espectral que o segue. Inigmigos atingidos pela sombra receberão dano mágico e serão atordoados por alguns segundos.',
'Dano causado: 125/200/375; Duração do atordoamento: 2/2.5/4',
2),
('Riven',
'Riven.png',
'Barragem de Energia',
'riven-barragem-de-energia.png',
'Riven avança, ganhando um escudo e executando um ataque causando dano mágico em inimigos próximos. A cada 3º conjuração, Riven salta no ar lançando para frente uma grande barragem de energia que causa dano mágico extra.',
'Quantidade de escudo: 175/250/750; Dano causado: 180/250/750; Dano da barragem: 300/450/1350',
4),
('Sejuani',
'Sejuani.png',
'Fogo de Artifício',
'sejuani-fogo-de-artificio.png',
'Sejuani lança um enorme fogo de artifício. Depois de um curto período, inimigos dentro da área de efeito recebem dano mágico e são atordoados por alguns segundos.',
'Dano causado: 100/200/800; Duração do atordoamento: 2.5/3/6',
4),
('Sett',
'Sett.png',
'Hora do Show',
'sett-hora-do-show.png',
'Sett carrega seu alvo pelos ares e o arremessa no chão, causando uma porcentagem da vida máxima do mesmo como dano mágico e um dano reduzido nos outros inimigos dentro de uma grande área.',
'Dano causado ao alvo: 40/60/400%; Dano causado à outros inimigos: 20/30/200%',
5),
('Shen',
'Shen.png',
'Corrida das Sombras',
'shen-corrida-das-sombras.png',
'Shen atravessa seu alvo, ganhando um escudo e atraindo os ataques de todos os inimigos adjacentes para si durante alguns segundos.',
'Quantidade de escudo: 500/800/4000; Duração da atração: 4/4/8',
4),
('Sylas',
'Sylas.png',
'Correntes Chicote',
'sylas-correntes-chicote.png',
'Sylas chicoteia suas correntes em uma linha de 3 hexes, causando dano mágico aos inimigos atingidos e aumentando o custo de sua próxima habilidade em 33%.',
'Dano causado: 250/400/700/1111',
2),
('Tahm Kench',
'TahmKench.png',
'Pele Grossa',
'tahm-kench-pele-grossa.png',
'Tahm Kench ignora uma certa quantidade de dano recebido de qualquer fonte.',
'Dano ignorado: 15/25/75',
1),
('Talon',
'Talon.png',
'Golpe Verdadeiro',
'talon-golpe-verdadeiro.png',
'Talon golpeia seu alvo, causando uma porcentagem de de seu dano de ataque. Se o golpe matar o mesmo, Talon torna-se imparável e inalvejável enquanto pula na direção do inimigo com menor armadura.',
'Dano causado: 240/250/275%',
4),
('Teemo',
'Teemo.png',
'Dardo Ofuscante',
'teemo-dardo-ofuscante.png',
'Teemo atira um dardo em seu alvo que explode em uma nuvem de esporos ao contato, envenenando inimigos próximos. Inimigos envenenados recebem dano mágico no decorrer de alguns segundos e são cegados no decorrer da duração.',
'Dano causado: 300/450/900; Duração do veneno: 2.5/3/4.5',
2),
('Thresh',
'Thresh.png',
'Lanterna Espectral',
'thresh-lanterna-espectral.png',
'Tresh joga sua lanterna para o aliado com menor vida atual, concendendo um escudo à ele e aos aliados próximos durante 4 segundos.',
'Quantidade de escudo: 250/450/750',
2),
('Twisted Fate',
'TwistedFate.png',
'Curingas',
'twisted-fate-curingas.png',
'Twisted Fate arremessa 3 cartas em um leque que causam dano mágico a qualquer inimigo atingido.',
'Dano causado: 250/350/475',
1),
('Vayne',
'Vayne.png',
'Dardos de Prata',
'vayne-dardos-de-prata.png',
'Passiva: Sempre que Vayne desferir 3 disparos contra o mesmo alvo, ela causará dano verdadeiro bônus.',
'Dano causado: 50/90/140',
1),
('Veigar',
'Veigar.png',
'Florecer Sombrio',
'veigar-florescer-sombrio.png',
'Veigar lança uma explosão de energia contra o inimigo com menor vida, causando dano mágico. Se isto matar o alvo, Veigar recebe um aumento permanente em seu poder de habilidade.',
'Dano causado: 450/600/900; Aumento de poder: 1/1/2',
3),
('Vi',
'Vi.png',
'Pancada Certeira',
'vi-pancada-certeira.png',
'A pancada de Vi atravessa seu alvo, causando dano mágico nos inimigos em um cone e reduzindo suas armaduras em uma porcentgem por 8 segundos.',
'Dano causado: 250/400/800; Redução de armadura: 40/60/80%',
2),
('Warwick',
'Warwick.png',
'Fome Eterna',
'warwick-fome-eterna.png',
'Warwick ganha velocidade de ataque, roubo de vida e se move mais rápido pelo resto do combate. Neste estado, se Warwick eliminar um inimigo, ele uiva, garantindo a si e a todos os aliados com os quais compartilha sinergias velocidade de ataque durante 3 segundos.',
'Velocidade de ataque: 135/150/500%; Roubo de vida: 40/40/200%; Velocidade de ataque do uivo: 60/75/200%',
4),
('Wukong',
'Wukong.png',
'Golpe Destruidor',
'wukong-golpe-destruidor.png',
'wukong golpeia seu alvo com seu bastão, causando uma porcentagem de seu dano de ataque como dano físico e atordoando-o por alguns segundos.',
'Dano causado: 250/265/280%; Duração do atordoamento: 1.5/2/3',
1),
('Xin Zhao',
'XinZhao.png',
'Guarda Crescente',
'xin-zhao-guarda-crescente.png',
'Xin Zhao varre seus arredores, causando uma porcentagem de sua dano de ataque em inimigos próximos e ganhando armadura e resistência mágica pelo restante do combate.',
'Dano causado: 300/325/350%; Aumento de armadura e resitência mágica: 50/60/75',
3),
('Yasuo',
'Yasuo.png',
'Tempestade de Aço',
'yasuo-tempestade-de-aco.png',
'Yasuo golpeia 2 hexes a sua frente, causando uma porcentagem de seu dano de ataque como dano físico e aplicando efeitos de contato.',
'Dano causado: 180/200/225%',
1),
('Yone',
'Yone.png',
'Destino Selado',
'yone-destino-selado.png',
'Yone atravessa uma grande área em sua frente, causando dano mágico dividido entre todos os inimigos atingidos, marcando-os para a morte, reduzindo suaarmadura e resistência mágica em 60% e liberando sua habilidade Inesquecível. Yone é inalvejável enquanto conjura a habilidade.; Inesquecível: Yone avança para o inimigo com a menor quantidade de vida que estiver marcado para a morte, causando dano aumentado.',
'Dano causado: 800/1300/9999; Dano de Inesquecível: 250/400/1000',
5),
('Yuumi',
'Yuumi.png',
'Frenesi',
'yuumi-frenesi.png',
'Yummi avança para perto de um aliado com pouca vida, curando-os por uma porcentagem de sua vida perdida e concedendo-os velocidade de ataque por 5 segundos. Ela, então, repete esta ação no aliado mais distânte.',
'Quantidade de cura: 30/45/75%; Velocidade de ataque: 30/40/60%',
3),
('Zed',
'Zed.png',
'Desprezo pelos Fracos',
'zed-desprezo-pelos-fracos.png',
'Passiva: a cada 3 ataques, Zed causa dano mágico bônus e rouba uma porcentagem do dano de ataque atual do alvo.',
'Dano causado: 45/50/75; Dano roubado: 25/30/35%',
2),
('Zilean',
'Zilean.png',
'Rebobinar Destinos',
'zilean-rebobinar-destino.png',
'Zilean conjura uma runa do tempo em alguns aliados com a menor vida (sem contar consigo mesmo). Quando estes aliados morrerem, eles renascem sem qualquer efeito negativo que possuíssem ao morrer. Depois de renascer, aliados possuem velocidade de ataque bônus pelo restante do combate.',
'Quantidade de aliados: 2/3/10; Tempo para ressurreição: 3.5/3/1; Vida ao ressuscitar: 350/500/3000',
5);
