/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2021-01-26 05:35:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Controlers;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import models.usuario;
import models.build;
import models.build;
import models.build;

public final class builder_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/Controlers/../Views/head.html", Long.valueOf(1610745455443L));
    _jspx_dependants.put("/Controlers/../Views/buildConstruct.jsp", Long.valueOf(1611352431291L));
    _jspx_dependants.put("/Controlers/../Views/navBar.jsp", Long.valueOf(1611106491161L));
    _jspx_dependants.put("/Controlers/../Views/buildList.jsp", Long.valueOf(1611092047777L));
    _jspx_dependants.put("/Controlers/../Views/foot.html", Long.valueOf(1611638818271L));
    _jspx_dependants.put("/Controlers/../Views/buildSelect.jsp", Long.valueOf(1610758559822L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("models.usuario");
    _jspx_imports_classes.add("models.build");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
 
	int userID = 0;
	
	if(session.getAttribute("userLogin") != null){	
		userID = (int) session.getAttribute("userLogin");
	}

	String acao = request.getParameter("acao") == null ? "S" : request.getParameter("acao");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("\t<head>\n");
      out.write("\t\t<meta charset=\"UTF-8\">\n");
      out.write("\t\t<meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("\t\t<meta http-equiv=\"content-type\" content=\"application/xhtml+xml; charset=UTF-8\">\n");
      out.write("\t\t\n");
      out.write("\t\t<link rel=\"shortcut icon\" href=\"../Imagens/Misc/favicon.png\" />\n");
      out.write("\t    <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.11.2/css/all.css\">\n");
      out.write("\t    <link rel=\"stylesheet\" href=\"../MDB/css/mdb.min.css\">\n");
      out.write("\t    <link rel=\"stylesheet\" href=\"../Styles/index.css\">\n");
      out.write("\t    \n");
      out.write("\t\t<title>TFT Builder set-4</title>\n");
      out.write("\t\t\n");
      out.write("\t</head>\n");
      out.write("\t\n");
      out.write("\t<body>\n");
      out.write("\t\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\n");
      out.write("\t\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.11/jquery.mask.min.js\"></script>\n");
      out.write("\t    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 
	int IDuser = 0;
	usuario user = new usuario();

	if(session.getAttribute("userLogin") != null){	
		IDuser = (int) session.getAttribute("userLogin");
		user = new usuario(IDuser);
		user.searchUser();
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <img\r\n");
      out.write("        src=\"../Imagens/Misc/Logo.png\"\r\n");
      out.write("        width=\"120\"\r\n");
      out.write("        alt=\"Logo\"\r\n");
      out.write("      />\r\n");
      out.write("    <button\r\n");
      out.write("      class=\"navbar-toggler\"\r\n");
      out.write("      type=\"button\"\r\n");
      out.write("      data-mdb-toggle=\"collapse\"\r\n");
      out.write("      data-mdb-target=\"#navbarNav\"\r\n");
      out.write("      aria-controls=\"navbarNav\"\r\n");
      out.write("      aria-expanded=\"false\"\r\n");
      out.write("      aria-label=\"Toggle navigation\"\r\n");
      out.write("    >\r\n");
      out.write("      <i class=\"fas fa-bars\"></i>\r\n");
      out.write("    </button>\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("      <ul class=\"navbar-nav fs-5\">\r\n");
      out.write("        <li class=\"nav-item ms-5\">\r\n");
      out.write("          <a class=\"nav-link\" aria-current=\"page\" href=\"../Controlers/index.jsp\">Menu</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item ms-5\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"../Controlers/builder.jsp\">Builder</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item ms-5\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"../Controlers/campeoes.jsp?acao=L\">Campeões</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item ms-5\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"../Controlers/sinergias.jsp?acao=L\">Sinergias</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        \r\n");
      out.write("        <!-- Avatar -->\r\n");
      out.write("        <li class=\"nav-item dropdown text-center\" id=\"icone_user\">\r\n");
      out.write("          <a\r\n");
      out.write("            class=\"nav-link dropdown-toggle d-flex align-items-center\"\r\n");
      out.write("            href=\"#\"\r\n");
      out.write("            id=\"dropDownUser\"\r\n");
      out.write("            role=\"button\"\r\n");
      out.write("            data-mdb-toggle=\"dropdown\"\r\n");
      out.write("            aria-expanded=\"false\"\r\n");
      out.write("          >\r\n");
      out.write("            <img\r\n");
      out.write("              src=\"../Imagens/Usuarios/");
      out.print(user.getFOTO() );
      out.write("\"\r\n");
      out.write("              class=\"rounded-circle\"\r\n");
      out.write("              width=\"40\"\r\n");
      out.write("              alt=\"ImagemPerfil\"\r\n");
      out.write("            />\r\n");
      out.write("          </a>\r\n");
      out.write("          \r\n");
      out.write("\t        <ul class=\"dropdown-menu me-5\" aria-labelledby=\"dropDownUser\">\r\n");
      out.write("\t          <li><a class=\"dropdown-item\" href=\"../Controlers/user.jsp\">Meus Dados</a></li>\r\n");
      out.write("\t          <li><a class=\"dropdown-item\" href=\"../Controlers/builder.jsp?acao=L\">Minhas Builds</a></li>\r\n");
      out.write("\t          ");
 if(user.getID_NIVEL() > 1) 
	          		out.write("<li><a class=\"dropdown-item\" href=\"../Controlers/user.jsp?acao=C\">Controle de Usuários</a></li>");
	          
      out.write("\r\n");
      out.write("\t          <li><a class=\"dropdown-item\" href=\"#\" id=\"disconnectUser\">Logout</a></li>\r\n");
      out.write("\t        </ul>\r\n");
      out.write("        \r\n");
      out.write("      \t</li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready( function() {\r\n");
      out.write("\t\t$(\"#disconnectUser\").click( function() {\r\n");
      out.write("\t\t\t$.get(\"../Models/disconnectUser.jsp\", function(data) {\r\n");
      out.write("\t\t\t\twindow.location.replace(\"../Controlers/index.jsp\");\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("\r\n");
 
	if(userID == 0){
		String redirectURL = "index.jsp";
	    response.sendRedirect(redirectURL);
	}else{

      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");
if(acao.equals("S")){ 
      out.write("\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
 
int idUser = 0;

if(session.getAttribute("userLogin") != null){	
	idUser = (int) session.getAttribute("userLogin");
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<div class=\"container mt-5\">\r\n");
      out.write("\t<div class=\"row text-center text-light\">\r\n");
      out.write("\t\t<div class=\"col border-end border-start border-warning\">\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"btn btn-outline-primary btn-floating btn-lg\" id=\"createBuild\" data-mdb-ripple-color=\"dark\">\r\n");
      out.write("\t\t\t  <i class=\"fas fa-plus\"></i>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<h4>Criar nova Build</h4>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col border-end border-warning\">\r\n");
      out.write("\t\t\t<a type=\"button\" class=\"btn btn-outline-primary btn-floating btn-lg\" id=\"buildBTN\" data-mdb-ripple-color=\"dark\" href=\"builder.jsp?acao=L\" >\r\n");
      out.write("\t\t\t  <i class=\"fas fa-list\"></i>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t<h4>Vizualizar minhas Builds</h4>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready( function() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#createBuild\").click( function() {\r\n");
      out.write("\t\t\t$.post(\"../Models/createBuild.jsp\", {idUser: ");
      out.print(idUser );
      out.write("}, function(data, status) {\r\n");
      out.write("\t\t\t\tif(data.success && data.id != 0){\r\n");
      out.write("\t\t\t\t\twindow.location.replace(\"../Controlers/builder.jsp?acao=C&id=\" + data.id);\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\twindow.alert(\"Ocorreu um erro ao criar uma nova build!\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}, \"json\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("</script>");
      out.write('\r');
      out.write('\n');
      out.write('	');
}else{ 
		if(acao.equals("L")){
      out.write("\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 
	int idUser = 0;
	build buildList = new build();
	
	if(session.getAttribute("userLogin") != null){	
		idUser = (int) session.getAttribute("userLogin");
		buildList = new build(idUser);
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<div class=\"container text-center text-light\">\r\n");
      out.write("\t<div class=\"row \">\r\n");
      out.write("\t\t<div class=\"col\">\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"btn btn-outline-primary\" title=\"Criar nova Build\" id=\"createBuild\" data-mdb-ripple-color=\"dark\">\r\n");
      out.write("\t\t\t  \t<i class=\"fas fa-plus\"></i>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"row row-cols-1 row-cols-md-3 g-4 mt-5 w-100\" id=\"buildList\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- A lista de builds do usuário carrega aqui -->\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready( function() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#buildList\").on(\"click\", \"button#delete\", function(e) {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.post(\"../Models/deleteBuild.jsp\", {\"delete\": this.value, \"userID\": ");
      out.print(idUser );
      out.write("}, function(data, status) {\r\n");
      out.write("\t\t\t\tif(data.success){\r\n");
      out.write("\t\t\t\t\twindow.alert(\"Build deletada com sucesso!\");\r\n");
      out.write("\t\t\t\t\tlocation.reload();\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\twindow.alert(\"Ocorreu um erro ao deletar a nova build!\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}, \"json\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.getJSON(\"../Models/createBuildList.jsp\", {idUser: ");
      out.print(idUser );
      out.write("}, function(data, status) {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar saida = \"\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar ids = data.id;\r\n");
      out.write("\t\t\tvar nomes = data.nome;\r\n");
      out.write("\t\t\tvar descrips = data.descrip;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfor(var i = 0; i < ids.length; i++){\r\n");
      out.write("\t\t\t\tsaida += \"<div class=\\\"col p-0 m-0\\\">\";\r\n");
      out.write("\t\t\t\tsaida += \"\t<div class=\\\"card mt-5 ms-5 text-light\\\" id=\\\"buildCard\\\" style=\\\"max-width: 540px\\\">\";\r\n");
      out.write("\t\t\t\tsaida += \"\t\t<div class=\\\"row g-0\\\">\";\r\n");
      out.write("\t\t\t\tsaida += \"\t\t\t<div class=\\\"col-md-3 border border-light\\\" id=\\\"buildImage\\\">\";\r\n");
      out.write("\t\t\t\tsaida += \"\t\t\t\t<img src=\\\"http://localhost:8080/TFTbuilder/Imagens/Misc/Pingu.png\\\" alt=\\\"Builds\\\" class=\\\"img-fluid\\\" />\";\r\n");
      out.write("\t\t\t\tsaida += \"\t\t\t</div>\";\r\n");
      out.write("\t\t\t\tsaida += \"\t\t\t<div class=\\\"col-md-9\\\">\";\r\n");
      out.write("\t\t\t\tsaida += \"\t\t\t\t<div class=\\\"card-body border border-light bg-primary\\\">\";\r\n");
      out.write("\t\t\t\tsaida += \"\t\t\t\t\t<h4 class=\\\"card-title bg-dark text-danger text-center\\\">\"+nomes[i]+\"</h4>\";\r\n");
      out.write("\t\t\t\tsaida += \"\t\t\t\t\t<p class=\\\"card-text\\\">\";\r\n");
      out.write("\t\t\t\tsaida += \"\t\t\t\t\t\t\"+descrips[i]+\"\";\r\n");
      out.write("\t\t\t\tsaida += \"\t\t\t\t\t</p>\";\r\n");
      out.write("\t\t\t\tsaida += \"\t\t\t\t\t<h5 class=\\\"card-text row\\\">\";\r\n");
      out.write("\t\t\t\tsaida += \"\t\t\t\t\t\t<a class=\\\"btn btn-primary col-2\\\" title=\\\"Editar Build\\\" style=\\\"background-color: #3b5998\\\" href=\\\"../Controlers/builder.jsp?acao=C&id=\"+ids[i]+\"\\\" role=\\\"button\\\">\";\r\n");
      out.write("\t\t\t\tsaida += \"\t\t\t\t\t\t\t<i class=\\\"far fa-edit\\\"></i>\";\r\n");
      out.write("\t\t\t\tsaida += \"\t\t\t\t\t\t</a>\";\r\n");
      out.write("\t\t\t\tsaida += \"\t\t\t\t\t\t<button class=\\\"btn btn-primary col-2\\\" title=\\\"Deletar Build\\\" id=\\\"delete\\\" value=\\\"\"+ids[i]+\"\\\" style=\\\"background-color: #FF8A80\\\" type=\\\"button\\\" >\";\r\n");
      out.write("\t\t\t\tsaida += \"\t\t\t\t\t\t\t<i class=\\\"fas fa-times\\\"></i>\";\r\n");
      out.write("\t\t\t\tsaida += \"\t\t\t\t\t\t</button>\";\r\n");
      out.write("\t\t\t\tsaida += \"\t\t\t\t\t</h5>\";\r\n");
      out.write("\t\t\t\tsaida += \"\t\t\t\t</div>\";\r\n");
      out.write("\t\t\t\tsaida += \"\t\t\t</div>\";\r\n");
      out.write("\t\t\t\tsaida += \"\t\t</div>\";\r\n");
      out.write("\t\t\t\tsaida += \"\t</div>\";\r\n");
      out.write("\t\t\t\tsaida += \"</div>\";\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(ids.length == 0){\r\n");
      out.write("\t\t\t\tsaida += \"<div class=\\\"col text-center text-light mx-auto border border-light p-5\\\">\";\r\n");
      out.write("\t\t\t\tsaida += \"\tVoce nao possui nenhuma build salva\";\r\n");
      out.write("\t\t\t\tsaida += \"</div>\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#buildList\").html(saida);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#createBuild\").click( function() {\r\n");
      out.write("\t\t\t$.post(\"../Models/createBuild.jsp\", {idUser: ");
      out.print(idUser );
      out.write("}, function(data, status) {\r\n");
      out.write("\t\t\t\tif(data.success && data.id != 0){\r\n");
      out.write("\t\t\t\t\twindow.location.replace(\"../Controlers/builder.jsp?acao=C&id=\" + data.id);\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\twindow.alert(\"Ocorreu um erro ao criar uma nova build!\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}, \"json\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("</script>");
      out.write('\r');
      out.write('\n');
      out.write('	');
	}else{ 
      out.write("\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");

	int ID = request.getParameter("id") == null ? 0 : Integer.parseInt(request.getParameter("id"));
	int idUser = 0;
	
	build construct = new build();
	construct.setID(ID);
	construct.searchBuild();
	
	if(session.getAttribute("userLogin") != null){	
		idUser = (int) session.getAttribute("userLogin");
	}

      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<div class=\"container mt-5 text-light\">\r\n");
      out.write("\t<div class=\"row text-center\">\r\n");
      out.write("\t\t<div class=\"col-1 p-3 border\">\r\n");
      out.write("\t\t\t<button class=\"btn btn-primary\" title=\"Salvar Alterações\" id=\"salvar\" style=\"background-color: #00B74A\" type=\"button\" >\r\n");
      out.write("\t\t\t\t<i class=\"fas fa-check\"></i>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-1 p-3 border\">\r\n");
      out.write("\t\t\t<button class=\"btn btn-primary\" title=\"Excluir Build\" id=\"excluir\" style=\"background-color: #F93154\" type=\"button\" >\r\n");
      out.write("\t\t\t\t<i class=\"fas fa-times\"></i>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-9\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-1 p-3 border\">\r\n");
      out.write("\t\t\t<button class=\"btn btn-primary\" title=\"Limpar Time\" id=\"limpar\" style=\"background-color: #1266F1\" type=\"button\" >\r\n");
      out.write("\t\t\t\t<i class=\"fas fa-broom\"></i>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<form method=\"POST\" class=\"row mb-0\" id=\"buildData\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"id\" value=\"");
      out.print(ID );
      out.write("\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"idUser\" value=\"");
      out.print(idUser );
      out.write("\">\r\n");
      out.write("\t\t<div class=\"col-2 border form-outline\">\r\n");
      out.write("\t\t\t<textarea id=\"nome\" name=\"nome\" class=\"form-control text-light\" rows=\"3\"> ");
      out.print(construct.getNOME() );
      out.write(" </textarea>\r\n");
      out.write("\t\t\t<label class=\"form-label text-warning\" for=\"nome\">Nome</label>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-10 border form-outline\"> \r\n");
      out.write("\t\t\t<textarea id=\"descrip\" name=\"descrip\" class=\"form-control text-light\" rows=\"3\"> ");
      out.print(construct.getDESCRIP() );
      out.write(" </textarea> \r\n");
      out.write("\t\t\t<label class=\"form-label text-warning\" for=\"descrip\">Descrição</label>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<div class=\"col-2 p-2 border\">\r\n");
      out.write("\t\t\t<div class=\"row row-cols-1 row-cols-md-2 g-2\" id=\"sinergiasDaBuild\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- As sinergias dos campeões da build carregam aqui -->\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-10 border\">\r\n");
      out.write("\t\t\t<div id=\"campeoesDaBuild\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<!-- Os campeões da Build carregam aqui -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"row\"><div class=\"col-md-5 p-0\"> <h2 class=\"border border-bottom-0 border-start-0 m-0 ps-3\"> Escolha seus campeões </h2> </div></div>\r\n");
      out.write("\t\t\t<div class=\"row row-cols-1 row-cols-md-6 border\" id=\"listaDeSelecao\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- Lista de campeões para escolher carrega aqui -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready( function() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#campeoesDaBuild\").on(\"click\", \"img\", function(e){\r\n");
      out.write("\t\t\t$.post(\"../Models/deleteChampFromBuild.jsp\", {\"champID\": this.id, \"buildID\": ");
      out.print(ID );
      out.write(", \"userID\": ");
      out.print(idUser );
      out.write("}, function(data, status) {\r\n");
      out.write("\t\t\t\tif(!data.success){\r\n");
      out.write("\t\t\t\t\twindow.alert(\"Opa! Parece que você acabou entrando na build de outra pessoa! Desculpe, mas você não pode alterar os dados aqui!\");\r\n");
      out.write("\t\t\t\t\twindow.location.replace(\"../Controlers/builder.jsp?acao=L\");\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\tlocation.reload();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}, \"json\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#listaDeSelecao\").on(\"click\", \"img\", function(e) {\r\n");
      out.write("\t\t\tvar IDparts = this.id.split(\"-\");\r\n");
      out.write("\t\t\tif(IDparts[0] == 0){\r\n");
      out.write("\t\t\t\t$.post(\"../Models/insertChampToBuild.jsp\", {\"champID\": IDparts[1], \"buildID\": ");
      out.print(ID );
      out.write(", \"userID\": ");
      out.print(idUser );
      out.write("}, function(data, status) {\r\n");
      out.write("\t\t\t\t\tif(!data.success){\r\n");
      out.write("\t\t\t\t\t\twindow.alert(data.message);\r\n");
      out.write("\t\t\t\t\t\twindow.location.replace(\"../Controlers/builder.jsp?acao=L\");\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\tlocation.reload();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}, \"json\");\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t$.post(\"../Models/deleteChampFromBuild.jsp\", {\"champID\": IDparts[1], \"buildID\": ");
      out.print(ID );
      out.write(", \"userID\": ");
      out.print(idUser );
      out.write("}, function(data, status) {\r\n");
      out.write("\t\t\t\t\tif(!data.success){\r\n");
      out.write("\t\t\t\t\t\twindow.alert(\"Opa! Parece que você acabou entrando na build de outra pessoa! Desculpe, mas você não pode alterar os dados aqui!\");\r\n");
      out.write("\t\t\t\t\t\twindow.location.replace(\"../Controlers/builder.jsp?acao=L\");\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\tlocation.reload();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}, \"json\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\te.preventDefault();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.getJSON(\"../Models/getBuildSynergies.jsp\", {\"buildID\": ");
      out.print(ID );
      out.write("}, function(data, status) {\r\n");
      out.write("\t\t\tif(data.success){\r\n");
      out.write("\t\t\t\tvar count = data.idCOUNT;\r\n");
      out.write("\t\t\t\tvar nomes = data.sinNOME;\r\n");
      out.write("\t\t\t\tvar fotos = data.sinFOTO;\r\n");
      out.write("\t\t\t\tvar marcas = data.sinMARCA;\r\n");
      out.write("\t\t\t\tvar QTD1 = data.sinQTD1;\r\n");
      out.write("\t\t\t\tvar QTD2 = data.sinQTD2;\r\n");
      out.write("\t\t\t\tvar QTD3 = data.sinQTD3;\r\n");
      out.write("\t\t\t\tvar QTD4 = data.sinQTD4;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar saida = \"\";\r\n");
      out.write("\t\t\t\tfor(var i = 0; i < count.length; i++){\r\n");
      out.write("\t\t\t\t\tif(count[i] < QTD1[i]){\r\n");
      out.write("\t\t\t\t\t\tsaida += \"<div class=\\\"col text-end w-25\\\">\";\r\n");
      out.write("\t\t\t\t\t\tsaida += \"  <img src=\\\"http://localhost:8080/TFTbuilder/Imagens/Sinergias/\"+fotos[i]+\"\\\" class=\\\"img-fluid rounded-circle\\\" alt=\\\"\"+nomes[i]+\"\\\" width=\\\"50px\\\" />\";\r\n");
      out.write("\t\t\t\t\t\tsaida += \"</div>\";\r\n");
      out.write("\t\t\t\t\t\tsaida += \"<div class=\\\"col w-75\\\">\";\r\n");
      out.write("\t\t\t\t\t\tsaida += \"  <small> Quantidade: \"+count[i]+\"/\"+QTD1[i]+\" </small>\";\r\n");
      out.write("\t\t\t\t\t\tsaida += \"  <br>\";\r\n");
      out.write("\t\t\t\t\t\tsaida += \"  <small> marca: 0/\"+marcas[i]+\" </small>\";\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\tif(count[i] >= QTD1[i] && (count[i] < QTD2[i] || QTD2[i] == 0)){\r\n");
      out.write("\t\t\t\t\t\t\tsaida += \"<div class=\\\"col text-end w-25\\\" id=\\\"marca0\\\">\";\r\n");
      out.write("\t\t\t\t\t\t\tsaida += \"  <img src=\\\"http://localhost:8080/TFTbuilder/Imagens/Sinergias/\"+fotos[i]+\"\\\" class=\\\"img-fluid rounded-circle\\\" alt=\\\"\"+nomes[i]+\"\\\" width=\\\"50px\\\" />\";\r\n");
      out.write("\t\t\t\t\t\t\tsaida += \"</div>\";\r\n");
      out.write("\t\t\t\t\t\t\tsaida += \"<div class=\\\"col w-75\\\" id=\\\"marca0\\\">\";\r\n");
      out.write("\t\t\t\t\t\t\tsaida += \"  <small> Quantidade: \"+count[i]+\"/\"+QTD2[i]+\" </small>\";\r\n");
      out.write("\t\t\t\t\t\t\tsaida += \"  <br>\";\r\n");
      out.write("\t\t\t\t\t\t\tsaida += \"  <small> marca: 1/\"+marcas[i]+\"(Bronze) </small>\";\r\n");
      out.write("\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\tif(count[i] >= QTD2[i] && (count[i] < QTD3[i] || QTD3[i] == 0)){\r\n");
      out.write("\t\t\t\t\t\t\t\tsaida += \"<div class=\\\"col text-end w-25\\\" id=\\\"marca1\\\">\";\r\n");
      out.write("\t\t\t\t\t\t\t\tsaida += \"  <img src=\\\"http://localhost:8080/TFTbuilder/Imagens/Sinergias/\"+fotos[i]+\"\\\" class=\\\"img-fluid rounded-circle\\\" alt=\\\"\"+nomes[i]+\"\\\" width=\\\"50px\\\" />\";\r\n");
      out.write("\t\t\t\t\t\t\t\tsaida += \"</div>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tsaida += \"<div class=\\\"col w-75\\\" id=\\\"marca1\\\">\";\r\n");
      out.write("\t\t\t\t\t\t\t\tsaida += \"  <small> Quantidade: \"+count[i]+\"/\"+QTD3[i]+\" </small>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tsaida += \"  <br>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tsaida += \"  <small> marca: 2/\"+marcas[i]+\"(Prata) </small>\";\r\n");
      out.write("\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\tif(count[i] >= QTD3[i] && (count[i] < QTD4[i] || QTD4[i] == 0)){\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsaida += \"<div class=\\\"col text-end w-25\\\" id=\\\"marca2\\\">\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsaida += \"  <img src=\\\"http://localhost:8080/TFTbuilder/Imagens/Sinergias/\"+fotos[i]+\"\\\" class=\\\"img-fluid rounded-circle\\\" alt=\\\"\"+nomes[i]+\"\\\" width=\\\"50px\\\" />\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsaida += \"</div>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsaida += \"<div class=\\\"col w-75\\\" id=\\\"marca2\\\">\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsaida += \"  <small> Quantidade: \"+count[i]+\"/\"+QTD4[i]+\" </small>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsaida += \"  <br>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsaida += \"  <small> marca: 3/\"+marcas[i]+\"(Ouro) </small>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsaida += \"<div class=\\\"col text-end w-25\\\" id=\\\"marca3\\\">\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsaida += \"  <img src=\\\"http://localhost:8080/TFTbuilder/Imagens/Sinergias/\"+fotos[i]+\"\\\" class=\\\"img-fluid rounded-circle\\\" alt=\\\"\"+nomes[i]+\"\\\" width=\\\"50px\\\" />\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsaida += \"</div>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsaida += \"<div class=\\\"col w-75\\\" id=\\\"marca3\\\">\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsaida += \"  <small> Quantidade: \"+count[i]+\"/\"+QTD4[i]+\" </small>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsaida += \"  <br>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsaida += \"  <small> marca: 4/\"+marcas[i]+\"(Platina) </small>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tsaida += \"</div>\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(count[0] == 0){\r\n");
      out.write("\t\t\t\t\tsaida = \"<h5>Sinergias...</h5>\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#sinergiasDaBuild\").html(saida);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.getJSON(\"../Models/getBuildChamps.jsp\", {\"buildID\": ");
      out.print(ID );
      out.write("}, function(data, status){\r\n");
      out.write("\t\t\tif(data.success){\r\n");
      out.write("\t\t\t\tvar sinNOMEs = data.sinNOME;\r\n");
      out.write("\t\t\t\tvar sinFOTOs = data.sinFOTO;\r\n");
      out.write("\t\t\t\tvar campIDs = data.campID;\r\n");
      out.write("\t\t\t\tvar campNOMEs = data.campNOME;\r\n");
      out.write("\t\t\t\tvar campFOTOs = data.campFOTO;\r\n");
      out.write("\t\t\t\tvar campTIPOs = data.campTIPO;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar saida = \"\";\r\n");
      out.write("\t\t\t\tsaida += \"<div class=\\\"row\\\"> <div class=\\\"col\\\"> <h4> Sua quantidade de campeões: \"+campIDs.length+\"/9 </h4> </div> </div>\";\r\n");
      out.write("\t\t\t\tif(campIDs.length != 0){\r\n");
      out.write("\t\t\t\t\tsaida += \"<div class=\\\"row row-cols-1 row-cols-md-5 p-5 g-5\\\" >\";\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\tsaida += \"<div class=\\\"row p-5\\\" >\";\r\n");
      out.write("\t\t\t\t\tsaida += \"<h1> Sua Build ainda está vazia, acrescente campeões ao clicar em suas imagens na lista abaixo! </h1>\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar divsClasses = [\"text-end\", \"text-center\", \"text-start\"];\r\n");
      out.write("\t\t\t\tvar IDaux = 0;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tfor(var i = 0; i < campIDs.length; i++){\r\n");
      out.write("\t\t\t\t\tsaida += \"<div class=\\\"col text-center p-3\\\">\";\r\n");
      out.write("\t\t\t\t\tsaida += \"  <div class=\\\"row row-cols-md-3\\\">\";\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tfor(var j = 0; j < 3; j++){\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tsaida += \"  <div class=\\\"col \"+divsClasses[j]+\"\\\">\";\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tif(j == 0 || j == 2){\r\n");
      out.write("\t\t\t\t\t\t\tif(campTIPOs[i] == 3)\r\n");
      out.write("\t\t\t\t\t\t\t\tsaida += \"<br>\";\r\n");
      out.write("\t\t\t\t\t\t\tsaida += \" <img src=\\\"http://localhost:8080/TFTbuilder/Imagens/Sinergias/\"+sinFOTOs[IDaux]+\"\\\" id=\\\"\"+campIDs[i]+\"\\\" class=\\\"img-fluid rounded-circle\\\" alt=\\\"\"+sinNOMEs[IDaux]+\"\\\" />\";\r\n");
      out.write("\t\t\t\t\t\t\tIDaux++;\r\n");
      out.write("\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\tif(campTIPOs[i] == 3){\r\n");
      out.write("\t\t\t\t\t\t\t\tsaida += \" <img src=\\\"http://localhost:8080/TFTbuilder/Imagens/Sinergias/\"+sinFOTOs[IDaux]+\"\\\" id=\\\"\"+campIDs[i]+\"\\\" class=\\\"img-fluid rounded-circle\\\" alt=\\\"\"+sinNOMEs[IDaux]+\"\\\" />\";\r\n");
      out.write("\t\t\t\t\t\t\t\tIDaux++;\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tsaida += \"  </div>\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tsaida += \"  </div>\";\r\n");
      out.write("\t\t\t\t\tsaida += \"  <img src=\\\"http://localhost:8080/TFTbuilder/Imagens/Campeoes/\"+campFOTOs[i]+\"\\\" class=\\\"img-fluid rounded-circle\\\" id=\\\"\"+campIDs[i]+\"\\\" alt=\\\"\"+campNOMEs[i]+\"\\\" width=\\\"70px\\\" />\";\r\n");
      out.write("\t\t\t\t\tsaida += \"</div>\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tsaida += \"</div>\"\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#campeoesDaBuild\").html(saida);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\twindow.alert(\"Erro ao carregar construtor de builds!\");\r\n");
      out.write("\t\t\t\twindow.location.replace(\"../Controlers/index.jsp\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.getJSON(\"../Models/createChampList.jsp\", {\"buildID\": ");
      out.print(ID );
      out.write("}, function(data, status){\r\n");
      out.write("\t\t\tif(data.success){\r\n");
      out.write("\t\t\t\tvar ids = data.id;\r\n");
      out.write("\t\t\t\tvar ativos = data.ativo;\r\n");
      out.write("\t\t\t\tvar nomes = data.nome;\r\n");
      out.write("\t\t\t\tvar fotos = data.foto;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar saida = \"\";\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tfor(var i=0; i<ids.length; i++){\r\n");
      out.write("\t\t\t\t\tsaida += \"<div class=\\\"col text-center p-3 border-end border-bottom\\\">\";\r\n");
      out.write("\t\t\t\t\tif(ativos[i] == 1)\r\n");
      out.write("\t\t\t\t\t\tsaida += \"\t<img src=\\\"http://localhost:8080/TFTbuilder/Imagens/Campeoes/\"+fotos[i]+\"\\\" style=\\\"filter: grayscale(100%);\\\" class=\\\"img-fluid rounded-circle\\\" id=\\\"\"+ativos[i]+\"-\"+ids[i]+\"\\\" alt=\\\"\"+nomes[i]+\"\\\" width=\\\"80px\\\"  />\";\r\n");
      out.write("\t\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t\tsaida += \"\t<img src=\\\"http://localhost:8080/TFTbuilder/Imagens/Campeoes/\"+fotos[i]+\"\\\" class=\\\"img-fluid rounded-circle\\\" id=\\\"\"+ativos[i]+\"-\"+ids[i]+\"\\\" alt=\\\"\"+nomes[i]+\"\\\" width=\\\"80px\\\"  />\";\r\n");
      out.write("\t\t\t\t\tsaida += \"<h5> \"+nomes[i]+\" </h5>\"\r\n");
      out.write("\t\t\t\t\tsaida += \"</div>\"\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t$(\"#listaDeSelecao\").html(saida);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\twindow.alert(\"Erro ao carregar construtor de builds!\");\r\n");
      out.write("\t\t\t\twindow.location.replace(\"../Controlers/index.jsp\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#salvar\").click( function() {\r\n");
      out.write("\t\t\tvar buildData = $(\"#buildData\").serialize();\r\n");
      out.write("\t\t\t$.post(\"../Models/saveBuildData.jsp\", buildData, function(data, status) {\r\n");
      out.write("\t\t\t\tif(data.success){\r\n");
      out.write("\t\t\t\t\twindow.alert(\"Dados da build alterados com sucesso!\");\r\n");
      out.write("\t\t\t\t\twindow.location.replace(\"../Controlers/builder.jsp?acao=L\");\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\twindow.alert(\"Opa! Parece que você acabou entrando na build de outra pessoa! Desculpe, mas você não pode alterar os dados aqui!\");\r\n");
      out.write("\t\t\t\t\twindow.location.replace(\"../Controlers/builder.jsp?acao=L\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}, \"json\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#excluir\").click( function() {\r\n");
      out.write("\t\t\t$.post(\"../Models/deleteBuild.jsp\", {\"delete\": ");
      out.print(ID );
      out.write(", \"userID\": ");
      out.print(idUser );
      out.write("}, function(data, status) {\r\n");
      out.write("\t\t\t\tif(data.success){\r\n");
      out.write("\t\t\t\t\twindow.alert(\"Build excluida com sucesso!\");\r\n");
      out.write("\t\t\t\t\twindow.location.replace(\"../Controlers/builder.jsp?acao=L\");\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\twindow.alert(\"Opa! Parece que você acabou entrando na build de outra pessoa! Desculpe, mas você não pode alterar os dados aqui!\");\r\n");
      out.write("\t\t\t\t\twindow.location.replace(\"../Controlers/builder.jsp?acao=L\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}, \"json\")\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#limpar\").click( function() {\r\n");
      out.write("\t\t\t$.post(\"../Models/cleanBuild.jsp\", {\"buildID\": ");
      out.print(ID );
      out.write(", \"userID\": ");
      out.print(idUser );
      out.write("}, function(data, status) {\r\n");
      out.write("\t\t\t\tif(data.success){\r\n");
      out.write("\t\t\t\t\tlocation.reload();\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\twindow.alert(\"Opa! Parece que você acabou entrando na build de outra pessoa! Desculpe, mas você não pode alterar os dados aqui!\");\r\n");
      out.write("\t\t\t\t\twindow.location.replace(\"../Controlers/builder.jsp?acao=L\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}, \"json\")\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("</script>");
      out.write('\r');
      out.write('\n');
      out.write('	');
}
	 }
	}
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\n");
      out.write("\t</body>\n");
      out.write("\t<script type=\"text/javascript\" src=\"../MDB/js/mdb.min.js\"></script>\t\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
