/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2021-01-26 05:31:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Controlers;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import models.usuario;
import models.usuario;
import models.campeao;
import models.campeao;
import models.campeao;

public final class campeoes_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/Controlers/../Views/head.html", Long.valueOf(1610745455443L));
    _jspx_dependants.put("/Controlers/../Views/champList.jsp", Long.valueOf(1611198511593L));
    _jspx_dependants.put("/Controlers/../Views/navBar.jsp", Long.valueOf(1611106491161L));
    _jspx_dependants.put("/Controlers/../Views/foot.html", Long.valueOf(1611638818271L));
    _jspx_dependants.put("/Controlers/../Views/champEdit.jsp", Long.valueOf(1611268630731L));
    _jspx_dependants.put("/Controlers/../Views/champDetail.jsp", Long.valueOf(1611176280312L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("models.usuario");
    _jspx_imports_classes.add("models.campeao");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
 
	int userID = 0;
	usuario userAdmin = new usuario();	
	
	if(session.getAttribute("userLogin") != null){	
		userID = (int) session.getAttribute("userLogin");
		userAdmin = new usuario(userID);
		userAdmin.searchUser();
	}

	String acao = request.getParameter("acao") == null ? "L" : request.getParameter("acao");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("\t<head>\n");
      out.write("\t\t<meta charset=\"UTF-8\">\n");
      out.write("\t\t<meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("\t\t<meta http-equiv=\"content-type\" content=\"application/xhtml+xml; charset=UTF-8\">\n");
      out.write("\t\t\n");
      out.write("\t\t<link rel=\"shortcut icon\" href=\"../Imagens/Misc/favicon.png\" />\n");
      out.write("\t    <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.11.2/css/all.css\">\n");
      out.write("\t    <link rel=\"stylesheet\" href=\"../MDB/css/mdb.min.css\">\n");
      out.write("\t    <link rel=\"stylesheet\" href=\"../Styles/index.css\">\n");
      out.write("\t    \n");
      out.write("\t\t<title>TFT Builder set-4</title>\n");
      out.write("\t\t\n");
      out.write("\t</head>\n");
      out.write("\t\n");
      out.write("\t<body>\n");
      out.write("\t\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\n");
      out.write("\t\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.11/jquery.mask.min.js\"></script>\n");
      out.write("\t    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 
	int IDuser = 0;
	usuario user = new usuario();

	if(session.getAttribute("userLogin") != null){	
		IDuser = (int) session.getAttribute("userLogin");
		user = new usuario(IDuser);
		user.searchUser();
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <img\r\n");
      out.write("        src=\"../Imagens/Misc/Logo.png\"\r\n");
      out.write("        width=\"120\"\r\n");
      out.write("        alt=\"Logo\"\r\n");
      out.write("      />\r\n");
      out.write("    <button\r\n");
      out.write("      class=\"navbar-toggler\"\r\n");
      out.write("      type=\"button\"\r\n");
      out.write("      data-mdb-toggle=\"collapse\"\r\n");
      out.write("      data-mdb-target=\"#navbarNav\"\r\n");
      out.write("      aria-controls=\"navbarNav\"\r\n");
      out.write("      aria-expanded=\"false\"\r\n");
      out.write("      aria-label=\"Toggle navigation\"\r\n");
      out.write("    >\r\n");
      out.write("      <i class=\"fas fa-bars\"></i>\r\n");
      out.write("    </button>\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("      <ul class=\"navbar-nav fs-5\">\r\n");
      out.write("        <li class=\"nav-item ms-5\">\r\n");
      out.write("          <a class=\"nav-link\" aria-current=\"page\" href=\"../Controlers/index.jsp\">Menu</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item ms-5\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"../Controlers/builder.jsp\">Builder</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item ms-5\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"../Controlers/campeoes.jsp?acao=L\">Campeões</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item ms-5\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"../Controlers/sinergias.jsp?acao=L\">Sinergias</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        \r\n");
      out.write("        <!-- Avatar -->\r\n");
      out.write("        <li class=\"nav-item dropdown text-center\" id=\"icone_user\">\r\n");
      out.write("          <a\r\n");
      out.write("            class=\"nav-link dropdown-toggle d-flex align-items-center\"\r\n");
      out.write("            href=\"#\"\r\n");
      out.write("            id=\"dropDownUser\"\r\n");
      out.write("            role=\"button\"\r\n");
      out.write("            data-mdb-toggle=\"dropdown\"\r\n");
      out.write("            aria-expanded=\"false\"\r\n");
      out.write("          >\r\n");
      out.write("            <img\r\n");
      out.write("              src=\"../Imagens/Usuarios/");
      out.print(user.getFOTO() );
      out.write("\"\r\n");
      out.write("              class=\"rounded-circle\"\r\n");
      out.write("              width=\"40\"\r\n");
      out.write("              alt=\"ImagemPerfil\"\r\n");
      out.write("            />\r\n");
      out.write("          </a>\r\n");
      out.write("          \r\n");
      out.write("\t        <ul class=\"dropdown-menu me-5\" aria-labelledby=\"dropDownUser\">\r\n");
      out.write("\t          <li><a class=\"dropdown-item\" href=\"../Controlers/user.jsp\">Meus Dados</a></li>\r\n");
      out.write("\t          <li><a class=\"dropdown-item\" href=\"../Controlers/builder.jsp?acao=L\">Minhas Builds</a></li>\r\n");
      out.write("\t          ");
 if(user.getID_NIVEL() > 1) 
	          		out.write("<li><a class=\"dropdown-item\" href=\"../Controlers/user.jsp?acao=C\">Controle de Usuários</a></li>");
	          
      out.write("\r\n");
      out.write("\t          <li><a class=\"dropdown-item\" href=\"#\" id=\"disconnectUser\">Logout</a></li>\r\n");
      out.write("\t        </ul>\r\n");
      out.write("        \r\n");
      out.write("      \t</li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready( function() {\r\n");
      out.write("\t\t$(\"#disconnectUser\").click( function() {\r\n");
      out.write("\t\t\t$.get(\"../Models/disconnectUser.jsp\", function(data) {\r\n");
      out.write("\t\t\t\twindow.location.replace(\"../Controlers/index.jsp\");\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("\r\n");
 
	if(userID == 0){
		String redirectURL = "index.jsp";
	    response.sendRedirect(redirectURL);
	}else{

      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");
if(acao.equals("L")){ 
      out.write("\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");

	int IDusuario = 0;
	usuario nivelUser = new usuario();
	
	if(session.getAttribute("userLogin") != null){	
		IDusuario = (int) session.getAttribute("userLogin");
		nivelUser = new usuario(IDusuario);
		nivelUser.searchUser();
	}
	
	if(nivelUser.getID_NIVEL() >= 3){
		out.write("<div class=\"container text-center mt-5\"> " +
					 "<div class=\"row\">" +
						 "<div class=\"col\">" +
							 "<button type=\"button\" class=\"btn btn-outline-primary\" title=\"Criar novo Campeão\" id=\"createChamp\" data-mdb-ripple-color=\"dark\">" +
							  	 "<i class=\"fas fa-plus\"></i>" +
							 "</button>" +
						 "</div>" +
					 "</div>" +
				 "</div>");
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"row row-cols-1 row-cols-md-3 g-4 w-100\" id=\"champList\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- A lista de campeões existentes vem aqui -->\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready( function() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#champList\").on(\"click\", \"button#excluirCamp\", function(e) {\r\n");
      out.write("\t\t\t$.post(\"../Models/deleteChamp.jsp\", {idChamp: this.value}, function(data, status) {\r\n");
      out.write("\t\t\t\tif(data.success){\r\n");
      out.write("\t\t\t\t\twindow.alert(\"Campeão apagado com sucesso!\");\r\n");
      out.write("\t\t\t\t\twindow.location.replace(\"../Controlers/campeoes.jsp?acao=L\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}, \"json\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#createChamp\").click(function() {\r\n");
      out.write("\t\t\t$.post(\"../Models/createChamp.jsp\", function(data, status) {\r\n");
      out.write("\t\t\t\twindow.alert(\"Novo campeão criado com sucesso! Redirecionando para edição dos dados...\");\r\n");
      out.write("\t\t\t\twindow.location.replace(\"../Controlers/campeoes.jsp?acao=E&id=\"+data.id+\"\");\r\n");
      out.write("\t\t\t}, \"json\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.getJSON(\"../Models/createChampList.jsp\", {\"buildID\": 0}, function(data, status){\r\n");
      out.write("\t\t\tvar ids = data.id;\r\n");
      out.write("\t\t\tvar nomes = data.nome;\r\n");
      out.write("\t\t\tvar fotos = data.foto;\r\n");
      out.write("\t\t\tvar custos = data.custo;\r\n");
      out.write("\t\t\tvar habs = data.hab;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar saida = \"\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfor(var i=0; i<ids.length; i++){\r\n");
      out.write("\t\t\t\tsaida += \"<div class=\\\"col p-0 m-0\\\">\";\r\n");
      out.write("\t\t\t\tsaida += \" <div class=\\\"card mt-5 ms-5 text-light\\\" id=\\\"campCard\\\" style=\\\"max-width: 540px\\\">\";\r\n");
      out.write("\t\t\t\tsaida += \"  <div class=\\\"row g-0\\\">\";\r\n");
      out.write("\t\t\t\tsaida += \"    <div class=\\\"col-md-3 border border-light\\\" id=\\\"campImage\\\">\";\r\n");
      out.write("\t\t\t\tsaida += \"\t\t<img src=\\\"http://localhost:8080/TFTbuilder/Imagens/Campeoes/\"+fotos[i]+\"\\\" alt=\\\" \"+ nomes[i] +\" \\\" class=\\\"img-fluid mt-4 ms-2\\\" id=\\\"campeaoCusto\"+custos[i]+\"\\\" />\";\r\n");
      out.write("\t\t\t\tsaida += \"    </div>\";\r\n");
      out.write("\t\t\t\tsaida += \"\t  <div class=\\\"col-md-9\\\">\";\r\n");
      out.write("\t\t\t\tsaida += \"      <div class=\\\"card-body border border-light bg-primary\\\">\";\r\n");
      out.write("                saida += \"        <h4 class=\\\"card-title bg-dark text-danger text-center\\\">\"+ nomes[i] +\"</h4>\";\r\n");
      out.write("\t\t\t\tsaida += \"        <p class=\\\"card-text\\\">\";\r\n");
      out.write("\t\t\t\tvar habDescrip_parts = habs[i].split(\";\");\r\n");
      out.write("\t\t\t\tsaida +=            habDescrip_parts[0];\r\n");
      out.write("\t\t\t\tsaida += \"        </p>\";\r\n");
      out.write("\t\t\t\tsaida += \"        <h5 class=\\\"card-text row\\\">\";\r\n");
      out.write("\t\t\t\tsaida += \"          <small class=\\\"col-3 text-danger\\\"> Custo: \" +custos[i]+ \"</small>\";\r\n");
      out.write("\t\t\t\t");
 if(nivelUser.getID_NIVEL() >= 3){ 
      out.write("\r\n");
      out.write("\t\t\t\t\tsaida += \"          <a class=\\\"btn btn-primary col-2\\\" title=\\\"Editar Campeao\\\" style=\\\"background-color: #FFA900\\\" href=\\\"../Controlers/campeoes.jsp?acao=E&id=\"+ids[i]+\"\\\" role=\\\"button\\\"> \";\r\n");
      out.write("\t\t\t\t\tsaida += \"          \t<i class=\\\"far fa-edit\\\"></i>\";\r\n");
      out.write("\t\t\t\t\tsaida += \"          </a>\";\r\n");
      out.write("\t\t\t\t\tsaida += \"          <div class=\\\"col-1\\\"> </div>\";\r\n");
      out.write("\t\t\t\t\tsaida += \"          <button class=\\\"btn btn-primary col-2\\\" title=\\\"Excluir Campeao\\\" style=\\\"background-color: #F93154\\\" id=\\\"excluirCamp\\\" value=\\\"\"+ids[i]+\"\\\" role=\\\"button\\\"> \";\r\n");
      out.write("\t\t\t\t\tsaida += \"          \t<i class=\\\"fas fa-times\\\"></i>\";\r\n");
      out.write("\t\t\t\t\tsaida += \"          </button>\";\r\n");
      out.write("\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\tsaida += \"          <div class=\\\"col-1\\\"> </div>\";\r\n");
      out.write("\t\t\t\tsaida += \"          <a class=\\\"btn btn-primary col-2\\\" title=\\\"Detalhar Campeao\\\" style=\\\"background-color: #39C0ED\\\" href=\\\"../Controlers/campeoes.jsp?acao=D&id=\"+ids[i]+\"\\\" role=\\\"button\\\"> \";\r\n");
      out.write("\t\t\t\tsaida += \"          \t<i class=\\\"fas fa-info-circle\\\"></i>\";\r\n");
      out.write("\t\t\t\tsaida += \"          </a>\\r\\n\" + \r\n");
      out.write("\t\t\t\t\t\t\"        </h5>\\r\\n\" + \r\n");
      out.write("\t\t\t\t\t\t\"      </div>\\r\\n\" + \r\n");
      out.write("\t\t\t\t\t\t\"    </div>\\r\\n\" + \r\n");
      out.write("\t\t\t\t\t\t\"  </div>\\r\\n\" + \r\n");
      out.write("\t\t\t\t\t\t\"</div>\";\r\n");
      out.write("\t\t\t\tsaida += \"</div>\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#champList\").html(saida);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write('\r');
      out.write('\n');
      out.write('	');
}else{ 
		if(acao.equals("D")){
      out.write("\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");

	int ID = request.getParameter("id") == null ? 0 : Integer.parseInt(request.getParameter("id"));

	campeao camp = new campeao(ID);
	camp.searchChamp();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container text-center mt-5\" id=\"champDetail\">\r\n");
      out.write("\t<div class=\"row mt-5 border border-warning\">\r\n");
      out.write("\t\t<div class=\"col-3 border-end border-warning pt-5\">\r\n");
      out.write("\t\t\t<h2> ");
      out.print(camp.getNOME() );
      out.write(" </h2>\r\n");
      out.write("\t\t\t<img\r\n");
      out.write("\t\t\t  src=\"../Imagens/Campeoes/");
      out.print(camp.getFOTO() );
      out.write("\"\r\n");
      out.write("\t\t\t  class=\"img-fluid rounded-circle\"\r\n");
      out.write("\t\t\t  alt=\"");
      out.print(camp.getNOME() );
      out.write("\"\r\n");
      out.write("\t\t\t  width=\"200px\"\r\n");
      out.write("\t\t\t  id=\"campeaoCusto");
      out.print(camp.getCUSTO() );
      out.write("\"\r\n");
      out.write("\t\t\t/>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<h4> Custo: <i class=\"fas fa-coins text-warning\"></i> ");
      out.print(camp.getCUSTO() );
      out.write(" </h4>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-9 mt-5\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<h3 class=\"text-start\"> Habilidade: </h3> \r\n");
      out.write("\t\t\t\t<div class=\"col-4\">\r\n");
      out.write("\t\t\t\t\t<img\r\n");
      out.write("\t\t\t\t\t  src=\"../Imagens/Habilidades/");
      out.print(camp.getHABILIDADE_FOTO() );
      out.write("\"\r\n");
      out.write("\t\t\t\t\t  class=\"img-fluid rounded\"\r\n");
      out.write("\t\t\t\t\t  alt=\"");
      out.print(camp.getHABILIDADE() );
      out.write("\"\r\n");
      out.write("\t\t\t\t\t  width=\"100px\"\r\n");
      out.write("\t\t\t\t\t/>\r\n");
      out.write("\t\t\t\t\t<h5> ");
      out.print(camp.getHABILIDADE() );
      out.write(" </h5>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-8 text-start\">\r\n");
      out.write("\t\t\t\t\t");

						String[] habDescrip_parts = camp.getHABILIDADE_DESCRIP().split(";");
						
						for(String hab : habDescrip_parts){
							out.write("<p>" + hab + "</p>");
						}
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<h4> Melhorias por Nivel: </h4>\r\n");
      out.write("\t\t\t\t\t");

						String[] nvlParts = camp.getHABILIDADE_NVL().split(";");
						for(String nvl : nvlParts){
							out.write("<p class=\"ms-5\">" + nvl + "</p>");
						}
					
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- Os detalhes das sinergias e dos campeões relacionados aparecem aqui -->\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready( function() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.getJSON(\"../Models/getChampData.jsp\", {\"champID\": ");
      out.print(ID );
      out.write("}, function(data, status){\r\n");
      out.write("\t\t\tvar SINids = data.SINid;\r\n");
      out.write("\t\t\tvar SINtipos = data.SINtipo;\r\n");
      out.write("\t\t\tvar SINnomes = data.SINnome;\r\n");
      out.write("\t\t\tvar SINfotos = data.SINfoto;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar CAMPidSINs = data.CAMPidSIN;\r\n");
      out.write("\t\t\tvar CAMPids = data.CAMPid;\r\n");
      out.write("\t\t\tvar CAMPnomes = data.CAMPnome;\r\n");
      out.write("\t\t\tvar CAMPfotos = data.CAMPfoto;\r\n");
      out.write("\t\t\tvar CAMPcustos = data.CAMPcusto;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar saida = \"\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfor(var i = 0; i < SINids.length; i++){\r\n");
      out.write("\t\t\t\tsaida += \"<div class=\\\"row border border-warning\\\">\";\r\n");
      out.write("\t\t\t\tsaida += \"\t<div class=\\\"col border-end border-warning pt-3\\\">\";\r\n");
      out.write("\t\t\t\tif(SINtipos[i] == \"O\")\r\n");
      out.write("\t\t\t\t\tsaida += \"\t\t<h4> Origen </h4>\";\r\n");
      out.write("\t\t\t\telse\r\n");
      out.write("\t\t\t\t\tsaida += \"\t\t<h4> Classe </h4>\";\r\n");
      out.write("\t\t\t\tsaida += \"\t</div>\";\r\n");
      out.write("\t\t\t\tsaida += \"</div>\";\r\n");
      out.write("\t\t\t\tsaida += \"<div class=\\\"row border border-warning\\\">\";\r\n");
      out.write("\t\t\t\tsaida += \"\t<div class=\\\"col border-end border-warning pt-1\\\">\";\r\n");
      out.write("\t\t\t\tsaida += \"\t\t<div class=\\\"row p-3\\\">\";\r\n");
      out.write("\t\t\t\tsaida += \"\t\t\t<div class=\\\"col-8\\\">\";\r\n");
      out.write("\t\t\t\tsaida += \"\t\t\t\t<h2> \"+ SINnomes[i] +\" </h2>\";\r\n");
      out.write("\t\t\t\tsaida += \"              <a href=\\\"../Controlers/sinergias.jsp?acao=D&id=\"+SINids[i]+\"\\\" > <img src=\\\"http://localhost:8080/TFTbuilder/Imagens/Sinergias/\"+SINfotos[i]+\"\\\" class=\\\"img-fluid rounded-circle\\\" alt=\\\"\"+ SINnomes[i] +\"\\\" width=\\\"100px\\\" /> </a>\";\r\n");
      out.write("\t\t\t\tsaida += \"\t\t\t</div>\";\r\n");
      out.write("\t\t\t\tsaida += \"\t\t\t<div class=\\\"col-4\\\">\";\r\n");
      out.write("\t\t\t\tif(SINtipos[i] == \"O\") {\r\n");
      out.write("\t\t\t\t\tsaida += \"\t\t\t\t<h4> Outros Campeoes da origem \"+ SINnomes[i] +\" </h4>\";\r\n");
      out.write("\t\t\t\t}else {\r\n");
      out.write("\t\t\t\t\tsaida += \"\t\t\t\t<h4> Outros Campeoes da classe \"+ SINnomes[i] +\" </h4>\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tsaida += \"\t\t\t\t<div class=\\\"row row-cols-1 row-cols-md-3 g-4\\\">\";\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tfor(var j = 0; j < CAMPids.length; j++){\r\n");
      out.write("\t\t\t\t\tif(CAMPidSINs[j] == SINids[i]) {\r\n");
      out.write("\t\t\t\t\t\tsaida += \"\t\t\t\t<div class=\\\"col\\\">\";\r\n");
      out.write("\t\t\t\t\t\tsaida += \"\t\t\t\t\t<a href=\\\"../Controlers/campeoes.jsp?acao=D&id=\"+CAMPids[j]+\"\\\" >\t<img src=\\\"http://localhost:8080/TFTbuilder/Imagens/Campeoes/\"+CAMPfotos[j]+\"\\\" class=\\\"img-fluid rounded-circle\\\" id=\\\"campeaoCusto\"+CAMPcustos[j]+\"\\\" alt=\\\"\"+CAMPnomes[j]+\"\\\" width=\\\"50px\\\" /> </a>\";\r\n");
      out.write("\t\t\t\t\t\tsaida += \"\t\t\t\t</div>\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tsaida += \"\t\t\t\t</div>\";\r\n");
      out.write("\t\t\t\tsaida += \"\t\t\t</div>\";\r\n");
      out.write("\t\t\t\tsaida += \"\t\t</div>\";\r\n");
      out.write("\t\t\t\tsaida += \"\t</div>\";\r\n");
      out.write("\t\t\t\tsaida += \"</div>\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#champDetail\").append(saida);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("</script>");
      out.write('\r');
      out.write('\n');
      out.write('	');
	}else{
			if(acao.equals("E") && userAdmin.getID_NIVEL() > 2){
      out.write("\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");

	int ID = request.getParameter("id") == null ? 0 : Integer.parseInt(request.getParameter("id"));

	campeao camp = new campeao(ID);
	camp.searchChamp();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<form class=\"container text-center mt-5\" id=\"champEdit\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"id\" value=\"");
      out.print(ID );
      out.write("\">\r\n");
      out.write("\t<div class=\"row mt-5 p-3\">\r\n");
      out.write("\t\t<div class=\"col-4 form-outline\"> \r\n");
      out.write("\t\t\t<input type=\"text\" name=\"nome\" id=\"nome\" class=\"form-control text-light\" required value=\"");
      out.print(camp.getNOME() );
      out.write("\" />\r\n");
      out.write("\t\t\t<label class=\"form-label text-warning\" for=\"nome\">Nome</label>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-1\"> </div>\r\n");
      out.write("\t\t<div class=\"col-4 form-outline\"> \r\n");
      out.write("\t\t\t<input type=\"text\" name=\"foto\" id=\"foto\" class=\"form-control text-light\" required value=\"");
      out.print(camp.getFOTO() );
      out.write("\" />\r\n");
      out.write("\t\t\t<label class=\"form-label text-warning\" for=\"foto\">Foto</label>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-1\"> </div>\r\n");
      out.write("\t\t<div class=\"col-2\"> \r\n");
      out.write("\t\t\t<label class=\"form-label text-warning\" for=\"custo\">Custo: </label>\r\n");
      out.write("\t\t\t<select name=\"custo\" id=\"custo\" required>\r\n");
      out.write("\t\t\t\t");
 
					String saida = "";
					for(int i = 1; i < 6; i++){
						if(i == camp.getCUSTO()){
							saida += "<option value=\""+camp.getCUSTO()+"\" selected=\"selected\"/> "+camp.getCUSTO()+" ";
						}else{
							saida += "<option value=\""+i+"\"/> "+i+" ";
						}
					}
					
					out.write(saida);
				
      out.write("\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"row mt-5 p-3\">\r\n");
      out.write("\t\t<div class=\"col-2\"> \r\n");
      out.write("\t\t\t<div class=\"form-outline\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"hab\" id=\"hab\" class=\"form-control text-light\" required value=\"");
      out.print(camp.getHABILIDADE() );
      out.write("\" />\r\n");
      out.write("\t\t\t\t<label class=\"form-label text-warning\" for=\"hab\">Habilidade</label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-3\"> \r\n");
      out.write("\t\t\t<div class=\"form-outline\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"habFoto\" id=\"habFoto\" class=\"form-control text-light\" required value=\"");
      out.print(camp.getHABILIDADE_FOTO() );
      out.write("\" />\r\n");
      out.write("\t\t\t\t<label class=\"form-label text-warning\" for=\"habFoto\">Habilidade-foto</label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-1\"></div>\r\n");
      out.write("\t\t<div class=\"col-6\">\r\n");
      out.write("\t\t\t<p class=\"text-danger\"> * Separe cada melhoria com ; (ponto e vírgula) * </p> \r\n");
      out.write("\t\t\t<div class=\"form-outline\">\r\n");
      out.write("\t\t\t\t<textarea name=\"habNivel\" rows=\"3\" id=\"habNivel\" class=\"form-control text-light\" required> ");
      out.print(camp.getHABILIDADE_NVL() );
      out.write(" </textarea> \r\n");
      out.write("\t\t\t\t<label class=\"form-label text-warning\" for=\"habNivel\">Habilidade-níveis</label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"row mt-5 p-3\">\r\n");
      out.write("\t\t<div class=\"col-3\"></div>\r\n");
      out.write("\t\t<div class=\"col-6 form-outline\"> \r\n");
      out.write("\t\t\t<textarea name=\"habDescrip\" rows=\"3\" id=\"habDescrip\" class=\"form-control text-light\" required> ");
      out.print(camp.getHABILIDADE_DESCRIP() );
      out.write(" </textarea> \r\n");
      out.write("\t\t\t<label class=\"form-label text-warning\" for=\"habDescrip\">Habilidade-descrição</label>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-3\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"row mt-5 p-3\" id=\"synergyData\">\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t<!-- O select com as sinergias do campeão carregam aqui -->\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"row mt-5 p-3\">\r\n");
      out.write("\t\t<button class=\"btn btn-primary col-1\" type=\"button\" title=\"Salvar Alterações\" style=\"background-color: #00B74A\" id=\"saveCamp\" value=\"");
      out.print(ID );
      out.write("\">\r\n");
      out.write("\t\t\t<i class=\"fas fa-check\"></i>\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\t\t<div class=\"col-1\"></div>\r\n");
      out.write("\t\t<button class=\"btn btn-primary col-1\" type=\"button\" title=\"Excluir Campeao\" style=\"background-color: #F93154\" id=\"excluirCamp\" value=\"");
      out.print(ID );
      out.write("\">\r\n");
      out.write("\t\t\t<i class=\"fas fa-times\"></i>\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready( function() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#synergyData\").on(\"change\", \"input#3Sin\", function(e) {\r\n");
      out.write("\t\t\t$(\"#sinergia3\").prop(\"hidden\", !this.checked);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#excluirCamp\").click(function() {\r\n");
      out.write("\t\t\t$.post(\"../Models/deleteChamp.jsp\", {idChamp: this.value}, function(data, status) {\r\n");
      out.write("\t\t\t\tif(data.success){\r\n");
      out.write("\t\t\t\t\twindow.alert(\"Campeão apagado com sucesso!\");\r\n");
      out.write("\t\t\t\t\twindow.location.replace(\"../Controlers/campeoes.jsp?acao=L\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}, \"json\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#saveCamp\").click(function() {\r\n");
      out.write("\t\t\tvar campData = $(\"#champEdit\").serialize();\r\n");
      out.write("\t\t\t$.post(\"../Models/changeChampData.jsp\", campData, function(data, status) {\r\n");
      out.write("\t\t\t\tif(data.success){\r\n");
      out.write("\t\t\t\t\twindow.alert(\"Dados de campeão alterados com sucesso!\");\r\n");
      out.write("\t\t\t\t\twindow.location.replace(\"../Controlers/campeoes.jsp?acao=L\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}, \"json\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.getJSON(\"../Models/getAllSynergys.jsp\", {\"champID\": ");
      out.print(ID );
      out.write("}, function(data, status) {\r\n");
      out.write("\t\t\tvar saida = \"\";\r\n");
      out.write("\t\t\tvar select1 = \"\";\r\n");
      out.write("\t\t\tvar select2 = \"\";\r\n");
      out.write("\t\t\tvar select3 = \"\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar ALLsinIDs = data.allID;\r\n");
      out.write("\t\t\tvar ALLsinNOMEs = data.allNOME;\r\n");
      out.write("\t\t\tvar CHAMPsinIDs = data.champID;\r\n");
      out.write("\t\t\tvar CHAMPsinNOMEs = data.champNOME;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfor(var i = 0; i < ALLsinIDs.length; i++){\r\n");
      out.write("\t\t\t\tif(ALLsinIDs[i] == CHAMPsinIDs[0]) {\r\n");
      out.write("\t\t\t\t\tselect1 += \"<option value=\\\"\"+CHAMPsinIDs[0]+\"\\\" selected=\\\"selected\\\"/> \"+CHAMPsinNOMEs[0]+\" \";\r\n");
      out.write("\t\t\t\t\tselect2 += \"<option value=\\\"\"+ALLsinIDs[i]+\"\\\" /> \"+ALLsinNOMEs[i]+\" \";\r\n");
      out.write("\t\t\t\t\tselect3 += \"<option value=\\\"\"+ALLsinIDs[i]+\"\\\" /> \"+ALLsinNOMEs[i]+\" \";\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\tif(ALLsinIDs[i] == CHAMPsinIDs[1]){\r\n");
      out.write("\t\t\t\t\t\tselect1 += \"<option value=\\\"\"+ALLsinIDs[i]+\"\\\" /> \"+ALLsinNOMEs[i]+\" \";\r\n");
      out.write("\t\t\t\t\t\tselect2 += \"<option value=\\\"\"+CHAMPsinIDs[1]+\"\\\" selected=\\\"selected\\\"/> \"+CHAMPsinNOMEs[1]+\" \";\r\n");
      out.write("\t\t\t\t\t\tselect3 += \"<option value=\\\"\"+ALLsinIDs[i]+\"\\\" /> \"+ALLsinNOMEs[i]+\" \";\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\tif(CHAMPsinIDs.length >= 3){\r\n");
      out.write("\t\t\t\t\t\t\tif(ALLsinIDs[i] == CHAMPsinIDs[2]){\r\n");
      out.write("\t\t\t\t\t\t\t\tselect1 += \"<option value=\\\"\"+ALLsinIDs[i]+\"\\\" /> \"+ALLsinNOMEs[i]+\" \";\r\n");
      out.write("\t\t\t\t\t\t\t\tselect2 += \"<option value=\\\"\"+ALLsinIDs[i]+\"\\\" /> \"+ALLsinNOMEs[i]+\" \";\r\n");
      out.write("\t\t\t\t\t\t\t\tselect3 += \"<option value=\\\"\"+CHAMPsinIDs[2]+\"\\\" selected=\\\"selected\\\"/> \"+CHAMPsinNOMEs[2]+\" \";\r\n");
      out.write("\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\tselect1 += \"<option value=\\\"\"+ALLsinIDs[i]+\"\\\" /> \"+ALLsinNOMEs[i]+\" \";\r\n");
      out.write("\t\t\t\t\t\t\t\tselect2 += \"<option value=\\\"\"+ALLsinIDs[i]+\"\\\" /> \"+ALLsinNOMEs[i]+\" \";\r\n");
      out.write("\t\t\t\t\t\t\t\tselect3 += \"<option value=\\\"\"+ALLsinIDs[i]+\"\\\" /> \"+ALLsinNOMEs[i]+\" \";\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\tselect1 += \"<option value=\\\"\"+ALLsinIDs[i]+\"\\\" /> \"+ALLsinNOMEs[i]+\" \";\r\n");
      out.write("\t\t\t\t\t\t\tselect2 += \"<option value=\\\"\"+ALLsinIDs[i]+\"\\\" /> \"+ALLsinNOMEs[i]+\" \";\r\n");
      out.write("\t\t\t\t\t\t\tselect3 += \"<option value=\\\"\"+ALLsinIDs[i]+\"\\\" /> \"+ALLsinNOMEs[i]+\" \";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(CHAMPsinIDs.length == 0){\r\n");
      out.write("\t\t\t\tselect1 += \"<option value=\\\"\\\" selected=\\\"selected\\\" disabled/> Escolha... \";\r\n");
      out.write("\t\t\t\tselect2 += \"<option value=\\\"\\\" selected=\\\"selected\\\" disabled/> Escolha... \";\r\n");
      out.write("\t\t\t\tselect3 += \"<option value=\\\"\\\" selected=\\\"selected\\\" disabled/> Escolha... \";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tsaida += \"<div class=\\\"col-3\\\">\";\r\n");
      out.write("\t\t\tsaida += \"\t<label class=\\\"form-label text-warning\\\" for=\\\"3Sin\\\">Campeão com 3 sinergias</label>\";\r\n");
      out.write("\t\t\tsaida += \"\t<input type=\\\"checkbox\\\" name=\\\"3Sin\\\" id=\\\"3Sin\\\" \";\r\n");
      out.write("\t\t\tsaida += CHAMPsinIDs.length >= 3 ? \"checked=\\\"checked\\\"\" : \" \"; \r\n");
      out.write("\t\t\tsaida += \"/>\";\r\n");
      out.write("\t\t\tsaida += \"</div>\";\r\n");
      out.write("\t\t\tsaida += \"<div class=\\\"col-1\\\">\";\r\n");
      out.write("\t\t\tsaida += \"\t<h5 class=\\\"text-warning text-end\\\">Sinergias: </h5>\";\r\n");
      out.write("\t\t\tsaida += \"</div>\";\r\n");
      out.write("\t\t\tsaida += \"<div class=\\\"col-1\\\" id=\\\"sinergias\\\">\";\r\n");
      out.write("\t\t\tsaida += \"\t<select name=\\\"sinergia1\\\" id=\\\"sinergia1\\\" required>\";\r\n");
      out.write("\t\t\tsaida += select1;\r\n");
      out.write("\t\t\tsaida += \"  </select>\";\r\n");
      out.write("\t\t\tsaida += \"\t<br> <br>\";\r\n");
      out.write("\t\t\tsaida += \"\t<select name=\\\"sinergia2\\\" id=\\\"sinergia2\\\" required>\";\r\n");
      out.write("\t\t\tsaida += select2;\r\n");
      out.write("\t\t\tsaida += \"\t</select>\";\r\n");
      out.write("\t\t\tsaida += \"\t<br> <br>\";\r\n");
      out.write("\t\t\tsaida += \"\t<select name=\\\"sinergia3\\\" id=\\\"sinergia3\\\" \";\r\n");
      out.write("\t\t\tsaida +=    CHAMPsinIDs.length < 3 ? \"hidden=\\\"true\\\"\" : \" \";\r\n");
      out.write("\t\t\tsaida += \"  >\";\r\n");
      out.write("\t\t\tsaida += select3;\r\n");
      out.write("\t\t\tsaida += \"\t</select>\";\r\n");
      out.write("\t\t\tsaida += \"</div>\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#synergyData\").html(saida);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("\t\t\t");
}else{
				String redirectURL = "index.jsp";
			    response.sendRedirect(redirectURL);
			}
		}
	  }
	}
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\n");
      out.write("\t</body>\n");
      out.write("\t<script type=\"text/javascript\" src=\"../MDB/js/mdb.min.js\"></script>\t\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\t");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
