/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2021-01-26 05:27:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Controlers;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import models.usuario;
import models.usuario;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/Controlers/../Views/head.html", Long.valueOf(1610745455443L));
    _jspx_dependants.put("/Controlers/../Views/welcomePage.jsp", Long.valueOf(1611352025046L));
    _jspx_dependants.put("/Controlers/../Views/navBar.jsp", Long.valueOf(1611106491161L));
    _jspx_dependants.put("/Controlers/../Views/foot.html", Long.valueOf(1611638818271L));
    _jspx_dependants.put("/Controlers/../Views/loginForm.html", Long.valueOf(1611106453624L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("models.usuario");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
 
	int userID = 0;

	if(session.getAttribute("userLogin") != null){	
		userID = (int) session.getAttribute("userLogin");
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("\t<head>\n");
      out.write("\t\t<meta charset=\"UTF-8\">\n");
      out.write("\t\t<meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("\t\t<meta http-equiv=\"content-type\" content=\"application/xhtml+xml; charset=UTF-8\">\n");
      out.write("\t\t\n");
      out.write("\t\t<link rel=\"shortcut icon\" href=\"../Imagens/Misc/favicon.png\" />\n");
      out.write("\t    <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.11.2/css/all.css\">\n");
      out.write("\t    <link rel=\"stylesheet\" href=\"../MDB/css/mdb.min.css\">\n");
      out.write("\t    <link rel=\"stylesheet\" href=\"../Styles/index.css\">\n");
      out.write("\t    \n");
      out.write("\t\t<title>TFT Builder set-4</title>\n");
      out.write("\t\t\n");
      out.write("\t</head>\n");
      out.write("\t\n");
      out.write("\t<body>\n");
      out.write("\t\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\n");
      out.write("\t\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.11/jquery.mask.min.js\"></script>\n");
      out.write("\t    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>");
      out.write("\r\n");
      out.write("\r\n");
 if(userID == 0){ 
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("<main>\n");
      out.write("\t<div class=\"container-fluid \">\n");
      out.write("\t\t<div class=\"row\">\n");
      out.write("\t\t\t<div class=\"col-3 \"> <img alt=\"Fachada\" class=\"ml-5 mt-5\" src=\"../Imagens/Misc/Fachada.png\" width=\"300px\">  </div>\n");
      out.write("\t\t\t<div class=\"mt-5 mx-auto  col-6\">\n");
      out.write("\t\t\t\t<form class=\"text-center border border-warning p-5 mt-5\" method=\"POST\" id=\"loginForm\">\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t    <p class=\"h4 mb-4\">Prossiga com o login para acessar o conteudo da pagina.</p>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t    <input type=\"text\" id=\"NomeOuEmail\" name=\"NomeOuEmail\" class=\"form-control mb-4\" placeholder=\"Nome de Usuario ou Email\">\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t    <input type=\"password\" id=\"senha\" name=\"senha\" class=\"form-control mb-4\" placeholder=\"Senha\">\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t    <button type=\"button\" class=\"btn btn-info\" id=\"submitForm\"> logar </button>\n");
      out.write("\t\t\t\t\t<br>\n");
      out.write("\t\t\t\t\t<br>\n");
      out.write("\t\t\t\t\t\t<div class=\"d-flex justify-content-around\">\n");
      out.write("\t\t\t\t\t        <p>\n");
      out.write("\t\t\t\t\t            Esqueceu a senha? <a href=\"../Controlers/recover.jsp\"> Recuperacao </a>\n");
      out.write("\t\t\t\t\t        </p>\n");
      out.write("\t\t\t\t\t    </div>\n");
      out.write("\t\t\t\t\t\t<h6> Ou </h6>\n");
      out.write("\t\t\t\t\t    <p>Ainda nao possui uma conta?\n");
      out.write("\t\t\t\t\t    \t<a href=\"../Controlers/register.jsp\"> Registro </a>\n");
      out.write("\t\t\t\t\t    </p>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\t<div id=\"retorno\" class=\"text-danger\"></div>\n");
      out.write("\t\t\t\t</form>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"col-3 align-self-end\"> <img alt=\"Fachada\"  src=\"../Imagens/Misc/Fachada.png\" width=\"300px\"> </div>\n");
      out.write("\t\t</div>\t\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"container mt-5\">\n");
      out.write("\t\t<div class=\"row mt-5\">\n");
      out.write("\t\t\t<img alt=\"Banner\" class=\"mx-auto mt-5 w-75\"  src=\"../Imagens/Misc/Banner.png\">\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t<script>\n");
      out.write("\t\t$(document).ready( () => {\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t$(\"#submitForm\").click( () => {\n");
      out.write("\t\t\t\tvar formData = $(\"#loginForm\").serialize();\n");
      out.write("\t\t\t\t$.post(\"../Models/testLogin.jsp\", formData, (data, status) => {\n");
      out.write("\t\t\t\t\tif(data.login){\n");
      out.write("\t\t\t\t\t\tlocation.reload();\n");
      out.write("\t\t\t\t\t}else{\n");
      out.write("\t\t\t\t\t\t$(\"#retorno\").html(\"Ocorrreu um erro no login!<br>Confira os dados de email e senha!\");\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t}, \"json\");\n");
      out.write("\t\t\t});\n");
      out.write("\t\t\t\n");
      out.write("\t\t});\n");
      out.write("\t</script>\n");
      out.write("</main>");
      out.write('\r');
      out.write('\n');
 }else{ 
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 
	int IDuser = 0;
	usuario user = new usuario();

	if(session.getAttribute("userLogin") != null){	
		IDuser = (int) session.getAttribute("userLogin");
		user = new usuario(IDuser);
		user.searchUser();
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <img\r\n");
      out.write("        src=\"../Imagens/Misc/Logo.png\"\r\n");
      out.write("        width=\"120\"\r\n");
      out.write("        alt=\"Logo\"\r\n");
      out.write("      />\r\n");
      out.write("    <button\r\n");
      out.write("      class=\"navbar-toggler\"\r\n");
      out.write("      type=\"button\"\r\n");
      out.write("      data-mdb-toggle=\"collapse\"\r\n");
      out.write("      data-mdb-target=\"#navbarNav\"\r\n");
      out.write("      aria-controls=\"navbarNav\"\r\n");
      out.write("      aria-expanded=\"false\"\r\n");
      out.write("      aria-label=\"Toggle navigation\"\r\n");
      out.write("    >\r\n");
      out.write("      <i class=\"fas fa-bars\"></i>\r\n");
      out.write("    </button>\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("      <ul class=\"navbar-nav fs-5\">\r\n");
      out.write("        <li class=\"nav-item ms-5\">\r\n");
      out.write("          <a class=\"nav-link\" aria-current=\"page\" href=\"../Controlers/index.jsp\">Menu</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item ms-5\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"../Controlers/builder.jsp\">Builder</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item ms-5\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"../Controlers/campeoes.jsp?acao=L\">Campeões</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item ms-5\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"../Controlers/sinergias.jsp?acao=L\">Sinergias</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        \r\n");
      out.write("        <!-- Avatar -->\r\n");
      out.write("        <li class=\"nav-item dropdown text-center\" id=\"icone_user\">\r\n");
      out.write("          <a\r\n");
      out.write("            class=\"nav-link dropdown-toggle d-flex align-items-center\"\r\n");
      out.write("            href=\"#\"\r\n");
      out.write("            id=\"dropDownUser\"\r\n");
      out.write("            role=\"button\"\r\n");
      out.write("            data-mdb-toggle=\"dropdown\"\r\n");
      out.write("            aria-expanded=\"false\"\r\n");
      out.write("          >\r\n");
      out.write("            <img\r\n");
      out.write("              src=\"../Imagens/Usuarios/");
      out.print(user.getFOTO() );
      out.write("\"\r\n");
      out.write("              class=\"rounded-circle\"\r\n");
      out.write("              width=\"40\"\r\n");
      out.write("              alt=\"ImagemPerfil\"\r\n");
      out.write("            />\r\n");
      out.write("          </a>\r\n");
      out.write("          \r\n");
      out.write("\t        <ul class=\"dropdown-menu me-5\" aria-labelledby=\"dropDownUser\">\r\n");
      out.write("\t          <li><a class=\"dropdown-item\" href=\"../Controlers/user.jsp\">Meus Dados</a></li>\r\n");
      out.write("\t          <li><a class=\"dropdown-item\" href=\"../Controlers/builder.jsp?acao=L\">Minhas Builds</a></li>\r\n");
      out.write("\t          ");
 if(user.getID_NIVEL() > 1) 
	          		out.write("<li><a class=\"dropdown-item\" href=\"../Controlers/user.jsp?acao=C\">Controle de Usuários</a></li>");
	          
      out.write("\r\n");
      out.write("\t          <li><a class=\"dropdown-item\" href=\"#\" id=\"disconnectUser\">Logout</a></li>\r\n");
      out.write("\t        </ul>\r\n");
      out.write("        \r\n");
      out.write("      \t</li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready( function() {\r\n");
      out.write("\t\t$(\"#disconnectUser\").click( function() {\r\n");
      out.write("\t\t\t$.get(\"../Models/disconnectUser.jsp\", function(data) {\r\n");
      out.write("\t\t\t\twindow.location.replace(\"../Controlers/index.jsp\");\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("</script>");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("<br>\r\n");
      out.write("<div>\r\n");
      out.write("\t<h1 class=\"text-warning text-center\"> Aprenda sobre as novidades da temporada DESTINOS de TeamFight Tactics </h1>\r\n");
      out.write("</div>  \r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container text-center mt-5 p-5\" id=\"mainMenu\">\r\n");
      out.write("\t<div class=\"mb-5 p-5 rounded-pill\" id=\"menuVideo\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<br><br><br>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col\">\r\n");
      out.write("\t\t\t\t<iframe class=\"border border-warning\" width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/5cM7YUmvle0\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"mt-5 mb-5 p-5 rounded-pill\" id=\"menuChamps\">\r\n");
      out.write("\t\t<div class=\"row mt-5\">\r\n");
      out.write("\t\t\t<div class=\"col\">\r\n");
      out.write("\t\t\t\t<img alt=\"Banner Campeões\" src=\"../Imagens/Misc/Banner_Campeoes.png\" width=\"400px\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br><br>\r\n");
      out.write("\t\t<div class=\"row mt-5\">\r\n");
      out.write("\t\t\t<div class=\"col-7\">\r\n");
      out.write("\t\t\t\t<h3> Descrubra tudo sobre os novos campeões! </h3>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col\">\r\n");
      out.write("\t\t\t\t<a class=\"btn btn-warning\" title=\"Visitar Campeões\" style=\"background-color: #FFA900; width: 100px; height: 50px\" href=\"../Controlers/campeoes.jsp?acao=L\" role=\"button\">\r\n");
      out.write("\t\t\t\t\t<span class=\"fs-4 text-primary\"> IR <i class=\"fas fa-chevron-right\"></i> </span>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br><br><br>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"mt-5 mb-5 p-5 rounded-pill\" id=\"menuSyns\">\r\n");
      out.write("\t\t<br><br>\r\n");
      out.write("\t\t<div class=\"row mt-5\">\r\n");
      out.write("\t\t\t<div class=\"col-7\">\r\n");
      out.write("\t\t\t\t<h3> Aprenda todos os poderes das sinergias! </h3>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col\">\r\n");
      out.write("\t\t\t\t<a class=\"btn btn-primary\" title=\"Visitar Sinergias\" style=\"background-color: #1266F1; width: 100px; height: 50px\" href=\"../Controlers/sinergias.jsp?acao=L\" role=\"button\">\r\n");
      out.write("\t\t\t\t\t<span class=\"fs-4 text-warning\"> IR <i class=\"fas fa-chevron-right\"></i> </span>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br><br>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"mt-5 mb-5 p-5 rounded-pill\" id=\"menuBuilder\">\r\n");
      out.write("\t\t<br><br>\r\n");
      out.write("\t\t<div class=\"row mt-5\">\r\n");
      out.write("\t\t\t<div class=\"col-7\">\r\n");
      out.write("\t\t\t\t<h3> Prepare-se antecipadamente para o campo de batalha, afiando suas estratégias e composições no construtor de equipes! </h3>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col\">\r\n");
      out.write("\t\t\t\t<a class=\"btn btn-warning\" title=\"Visitar Builder\" style=\"background-color: #FFA900; width: 100px; height: 50px\" href=\"../Controlers/builder.jsp\" role=\"button\">\r\n");
      out.write("\t\t\t\t\t<span class=\"fs-4 text-primary\"> IR <i class=\"fas fa-chevron-right\"></i> </span>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br><br>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\n");
      out.write("\t</body>\n");
      out.write("\t<script type=\"text/javascript\" src=\"../MDB/js/mdb.min.js\"></script>\t\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\t");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
