/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2021-01-26 05:30:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Controlers;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import models.usuario;
import models.nivelusuario;
import models.usuario;

public final class user_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/Controlers/../Views/head.html", Long.valueOf(1610745455443L));
    _jspx_dependants.put("/Controlers/../Views/navBar.jsp", Long.valueOf(1611106491161L));
    _jspx_dependants.put("/Controlers/../Views/usersControlPanel.jsp", Long.valueOf(1611105775475L));
    _jspx_dependants.put("/Controlers/../Views/userData.jsp", Long.valueOf(1611092597023L));
    _jspx_dependants.put("/Controlers/../Views/foot.html", Long.valueOf(1611638818271L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("models.nivelusuario");
    _jspx_imports_classes.add("models.usuario");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
 
	int userID = 0;
	usuario nivelUser = new usuario();
	String acao = request.getParameter("acao") == null ? "L" : request.getParameter("acao");
	
	if(session.getAttribute("userLogin") != null){	
		userID = (int) session.getAttribute("userLogin");
		nivelUser = new usuario(userID);
		nivelUser.searchUser();
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("\t<head>\n");
      out.write("\t\t<meta charset=\"UTF-8\">\n");
      out.write("\t\t<meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("\t\t<meta http-equiv=\"content-type\" content=\"application/xhtml+xml; charset=UTF-8\">\n");
      out.write("\t\t\n");
      out.write("\t\t<link rel=\"shortcut icon\" href=\"../Imagens/Misc/favicon.png\" />\n");
      out.write("\t    <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.11.2/css/all.css\">\n");
      out.write("\t    <link rel=\"stylesheet\" href=\"../MDB/css/mdb.min.css\">\n");
      out.write("\t    <link rel=\"stylesheet\" href=\"../Styles/index.css\">\n");
      out.write("\t    \n");
      out.write("\t\t<title>TFT Builder set-4</title>\n");
      out.write("\t\t\n");
      out.write("\t</head>\n");
      out.write("\t\n");
      out.write("\t<body>\n");
      out.write("\t\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\n");
      out.write("\t\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.11/jquery.mask.min.js\"></script>\n");
      out.write("\t    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 
	int IDuser = 0;
	usuario user = new usuario();

	if(session.getAttribute("userLogin") != null){	
		IDuser = (int) session.getAttribute("userLogin");
		user = new usuario(IDuser);
		user.searchUser();
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <img\r\n");
      out.write("        src=\"../Imagens/Misc/Logo.png\"\r\n");
      out.write("        width=\"120\"\r\n");
      out.write("        alt=\"Logo\"\r\n");
      out.write("      />\r\n");
      out.write("    <button\r\n");
      out.write("      class=\"navbar-toggler\"\r\n");
      out.write("      type=\"button\"\r\n");
      out.write("      data-mdb-toggle=\"collapse\"\r\n");
      out.write("      data-mdb-target=\"#navbarNav\"\r\n");
      out.write("      aria-controls=\"navbarNav\"\r\n");
      out.write("      aria-expanded=\"false\"\r\n");
      out.write("      aria-label=\"Toggle navigation\"\r\n");
      out.write("    >\r\n");
      out.write("      <i class=\"fas fa-bars\"></i>\r\n");
      out.write("    </button>\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("      <ul class=\"navbar-nav fs-5\">\r\n");
      out.write("        <li class=\"nav-item ms-5\">\r\n");
      out.write("          <a class=\"nav-link\" aria-current=\"page\" href=\"../Controlers/index.jsp\">Menu</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item ms-5\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"../Controlers/builder.jsp\">Builder</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item ms-5\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"../Controlers/campeoes.jsp?acao=L\">Campeões</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item ms-5\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"../Controlers/sinergias.jsp?acao=L\">Sinergias</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        \r\n");
      out.write("        <!-- Avatar -->\r\n");
      out.write("        <li class=\"nav-item dropdown text-center\" id=\"icone_user\">\r\n");
      out.write("          <a\r\n");
      out.write("            class=\"nav-link dropdown-toggle d-flex align-items-center\"\r\n");
      out.write("            href=\"#\"\r\n");
      out.write("            id=\"dropDownUser\"\r\n");
      out.write("            role=\"button\"\r\n");
      out.write("            data-mdb-toggle=\"dropdown\"\r\n");
      out.write("            aria-expanded=\"false\"\r\n");
      out.write("          >\r\n");
      out.write("            <img\r\n");
      out.write("              src=\"../Imagens/Usuarios/");
      out.print(user.getFOTO() );
      out.write("\"\r\n");
      out.write("              class=\"rounded-circle\"\r\n");
      out.write("              width=\"40\"\r\n");
      out.write("              alt=\"ImagemPerfil\"\r\n");
      out.write("            />\r\n");
      out.write("          </a>\r\n");
      out.write("          \r\n");
      out.write("\t        <ul class=\"dropdown-menu me-5\" aria-labelledby=\"dropDownUser\">\r\n");
      out.write("\t          <li><a class=\"dropdown-item\" href=\"../Controlers/user.jsp\">Meus Dados</a></li>\r\n");
      out.write("\t          <li><a class=\"dropdown-item\" href=\"../Controlers/builder.jsp?acao=L\">Minhas Builds</a></li>\r\n");
      out.write("\t          ");
 if(user.getID_NIVEL() > 1) 
	          		out.write("<li><a class=\"dropdown-item\" href=\"../Controlers/user.jsp?acao=C\">Controle de Usuários</a></li>");
	          
      out.write("\r\n");
      out.write("\t          <li><a class=\"dropdown-item\" href=\"#\" id=\"disconnectUser\">Logout</a></li>\r\n");
      out.write("\t        </ul>\r\n");
      out.write("        \r\n");
      out.write("      \t</li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready( function() {\r\n");
      out.write("\t\t$(\"#disconnectUser\").click( function() {\r\n");
      out.write("\t\t\t$.get(\"../Models/disconnectUser.jsp\", function(data) {\r\n");
      out.write("\t\t\t\twindow.location.replace(\"../Controlers/index.jsp\");\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("\r\n");
 if(userID == 0){
	String redirectURL = "index.jsp";
	response.sendRedirect(redirectURL);
}else{ 
	if(acao.equals("L")){
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
 
	int userId = 0;
	
	usuario userData = new usuario();
	nivelusuario nivel = new nivelusuario();
	
	if(session.getAttribute("userLogin") != null){	
		userId = (int) session.getAttribute("userLogin");
		
		userData = new usuario(userId);
		userData.searchUser();
		
		nivel = new nivelusuario(userData.getID_NIVEL());
		nivel.searchLevel();
	}

      out.write("\r\n");
      out.write("   \r\n");
      out.write("<div class=\"mt-5 mx-auto w-50\">\r\n");
      out.write("\t<form class=\"text-center border border-warning p-5 mt-5\" method=\"POST\" id=\"userForm\">\r\n");
      out.write("\t  <!-- 2 column grid layout with text inputs for the first and last names -->\r\n");
      out.write("\t  <div class=\"row mb-4\">\r\n");
      out.write("\t    <div class=\"col\">\r\n");
      out.write("\t      <div class=\"form-outline\">\r\n");
      out.write("\t        <input type=\"text\" id=\"nome\" name=\"nome\" class=\"form-control text-light\" value=\"");
      out.print(userData.getNOME() );
      out.write("\" />\r\n");
      out.write("\t        <label class=\"form-label text-warning\" for=\"nome\">Nome</label>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <div class=\"col\">\r\n");
      out.write("\t      <div class=\"form-outline\">\r\n");
      out.write("\t        <input type=\"text\" id=\"foto\" name=\"foto\" class=\"form-control text-light\" value=\"");
      out.print(userData.getFOTO() );
      out.write("\" />\r\n");
      out.write("\t        <label class=\"form-label text-warning\" for=\"foto\">Foto</label>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t\r\n");
      out.write("\t  <!-- Text input -->\r\n");
      out.write("\t  <div class=\"form-outline mb-4\">\r\n");
      out.write("\t    <input type=\"text\" id=\"email\" name=\"email\" class=\"form-control text-light\" value=\"");
      out.print(userData.getEMAIL() );
      out.write("\" />\r\n");
      out.write("\t    <label class=\"form-label text-warning\" for=\"email\">E-mail</label>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t\r\n");
      out.write("\t  <!-- Text input -->\r\n");
      out.write("\t  <div class=\"row mb-4\">\r\n");
      out.write("\t    <div class=\"col-11\">\r\n");
      out.write("\t      <div class=\"form-outline\">\r\n");
      out.write("\t        <input type=\"password\" id=\"senha\" name=\"senha\" class=\"form-control text-light\" value=\"");
      out.print(userData.getSENHA() );
      out.write("\"/>\r\n");
      out.write("\t    \t<label class=\"form-label text-warning\" for=\"senha\">Senha</label>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <div class=\"col-1\" title=\"Mostrar/Esconder senha\">\r\n");
      out.write("\t    \t<button type=\"button\" class=\"btn btn-primary btn-floating\" id=\"showPass\">\r\n");
      out.write("\t\t\t\t<i class=\"fas fa-eye-slash\" id=\"icon\"></i>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t  \r\n");
      out.write("\t  <!-- Text input -->\r\n");
      out.write("\t  <div class=\"row mb-4\">\r\n");
      out.write("\t    <div class=\"col-10\">\r\n");
      out.write("\t      <div class=\"form-outline\">\r\n");
      out.write("\t        <input type=\"text\" id=\"nivel\" name=\"nivel\" class=\"form-control\" value=\"");
      out.print(nivel.getNOME() );
      out.write("\" disabled />\r\n");
      out.write("\t    \t<label class=\"form-label text-warning\" for=\"nivel\">Seu Nivel</label>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <div class=\"col-2\" title=\"Solicitar aumento de cargo\">\r\n");
      out.write("\t    \t<button type=\"button\" class=\"btn btn-primary\" id=\"requestLevel\">\r\n");
      out.write("\t\t\t  <i class=\"fas fa-angle-double-up\"></i>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t  \r\n");
      out.write("\t  <input type=\"hidden\" value=\"");
      out.print(userData.getID() );
      out.write("\" name=\"idUser\"/>\r\n");
      out.write("\t  <input type=\"hidden\" value=\"");
      out.print(nivel.getID() );
      out.write("\" name=\"idNivel\"/>\r\n");
      out.write("\t  \t\r\n");
      out.write("\t  <!-- Submit button -->\r\n");
      out.write("\t  <div class=\"text-center\">\r\n");
      out.write("\t\t<button type=\"button\" class=\"btn btn-info\" onclick=\"window.history.back()\"> Voltar </button>\r\n");
      out.write("\t\t<button type=\"button\" class=\"btn btn-info\" id=\"submitForm\"> Alterar </button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <br>\r\n");
      out.write("      <div id=\"retorno\" class=\"text-danger\"></div>\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready( function() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#submitForm\").click( function() {\r\n");
      out.write("\t\t\tvar formData = $(\"#userForm\").serialize();\r\n");
      out.write("\t\t\t$.post(\"../Models/changeUserData.jsp\", formData, function(data, status) {\r\n");
      out.write("\t\t\t\tif(data.success){\r\n");
      out.write("\t\t\t\t\twindow.alert(\"Dados alterados com sucesso!\");\r\n");
      out.write("\t\t\t\t\twindow.location.replace(\"../Controlers/index.jsp\");\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t$(\"#retorno\").html(\"Ocorrreu um erro! Verifique os dados inceridos.\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}, \"json\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#requestLevel\").click( function() {\r\n");
      out.write("\t\t\tvar formData = $(\"#userForm\").serialize();\r\n");
      out.write("\t\t\t$.post(\"../Models/createRequest.jsp\", formData, function(data, status) {\r\n");
      out.write("\t\t\t\tif(data.success){\r\n");
      out.write("\t\t\t\t\twindow.alert(\"Aumento de nivel requisitado, aguarde por uma resposta via e-mail!\");\r\n");
      out.write("\t\t\t\t\twindow.location.replace(\"../Controlers/index.jsp\");\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t$(\"#retorno\").html(data.message);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}, \"json\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#showPass\").click(function() {\r\n");
      out.write("\t\t\tvar pass = document.getElementById(\"senha\");\r\n");
      out.write("\t\t\tvar icon = document.getElementById(\"icon\");\r\n");
      out.write("\t\t\tif(pass.type == \"text\"){\r\n");
      out.write("\t\t\t\tpass.type = \"password\";\r\n");
      out.write("\t\t\t\t$('.fa-eye').toggleClass('fa-eye fa-eye-slash');\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tpass.type = \"text\";\r\n");
      out.write("\t\t\t\t$('.fa-eye-slash').toggleClass('fa-eye-slash fa-eye');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("\t\r\n");
 }else{
		if(nivelUser.getID_NIVEL() > 1){ 
      out.write("\r\n");
      out.write("\t\t\t");
      out.write('\r');
      out.write('\n');

	int userId = 0;
	String painel = request.getParameter("painel") == null ? "L" : request.getParameter("painel");
	if(session.getAttribute("userLogin") != null){	
		userId = (int) session.getAttribute("userLogin");
	}

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<div class=\"container mt-5\">\r\n");
      out.write("\t<div class=\"row text-center mb-3\">\r\n");
      out.write("\t\t<div class=\"col-2\">\r\n");
      out.write("\t\t\t<a type=\"button\" class=\"btn btn-primary ");
      out.print(painel.equals("L")?"active":"" );
      out.write("\" href=\"../Controlers/user.jsp?acao=C&painel=L\"> \r\n");
      out.write("\t\t\t\tLista de Usuários \r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-8\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-2\">\r\n");
      out.write("\t\t\t<a type=\"button\" class=\"btn btn-primary ");
      out.print(painel.equals("R")?"active":"" );
      out.write("\" href=\"../Controlers/user.jsp?acao=C&painel=R\"> \r\n");
      out.write("\t\t\t\tLista de Requisições\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");

		String saida = "";
		if(painel.equals("L")){
			saida += "<div class=\"row\">";
			saida += "<table class=\"table table-bordered border-light text-light text-center\" id=\"userList\">";
			saida += "<tr class=\"bg-dark\">";
			saida += "<th class=\"p-2\"> # </th> <th class=\"p-2\"> ID </th> <th class=\"p-2\"> NOME </th> <th class=\"p-2\"> EMAIL </th> <th class=\"p-2\"> Excluir Usuário </th>";
			saida += "</tr>";
			saida += "<!-- Dados dos usuários existntes carregam aqui -->";
			saida += "</table>";
			saida += "</div>";
			out.write(saida);
		}else{
			if(painel.equals("R")){
				saida += "<div class=\"row\">";
				saida += "<table class=\"table table-bordered border-light text-light text-center\" id=\"requestList\">";
				saida += "<tr class=\"bg-dark\">";
				saida += "<th class=\"p-2\"> # </th> <th class=\"p-2\"> ID </th> <th class=\"p-2\"> NOME </th> <th class=\"p-2\"> NIVEL ATUAL </th> <th class=\"p-2\"> NIVEL ALMEJADO </th> <th class=\"p-2\"> AÇÕES </th>";
				saida += "</tr>";
				saida += "<!-- Dados das requisições existntes carregam aqui -->";
				saida += "</table>";
				saida += "</div>";
				out.write(saida);
			}
		}
	 
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready( function() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#userList\").on(\"click\", \"button\", function(e) {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.post(\"../Models/deleteUser.jsp\", {idUser: this.value}, function(data, status) {\r\n");
      out.write("\t\t\t\twindow.alert(\"Usuário excluído com sucesso\");\r\n");
      out.write("\t\t\t\tlocation.reload();\r\n");
      out.write("\t\t\t}, \"json\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#requestList\").on(\"click\", \"button\", function(e) {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.post(\"../Models/deleteRequest.jsp\", {idReq: this.value, acao: this.id}, function(data, status) {\r\n");
      out.write("\t\t\t\twindow.alert(data.message);\r\n");
      out.write("\t\t\t\tlocation.reload();\r\n");
      out.write("\t\t\t}, \"json\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.getJSON(\"../Models/createUserList.jsp\", {idUser: ");
      out.print(userId );
      out.write("}, function(data, status) {\r\n");
      out.write("\t\t\tvar saida = \"\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar ids = data.id;\r\n");
      out.write("\t\t\tvar nomes = data.nome;\r\n");
      out.write("\t\t\tvar emails = data.email;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfor(var i = 0; i < ids.length; i++){\r\n");
      out.write("\t\t\t\tsaida += \"<tr>\";\r\n");
      out.write("\t\t\t\tsaida += \"<td class=\\\"p-2\\\">\" + (i+1) + \r\n");
      out.write("\t\t\t\t\"</td> <td class=\\\"p-2\\\">\" + ids[i] + \r\n");
      out.write("\t\t\t\t\"</td> <td class=\\\"p-2\\\">\" + nomes[i] + \r\n");
      out.write("\t\t\t\t\"</td> <td class=\\\"p-2\\\">\" + emails[i] + \r\n");
      out.write("\t\t\t\t\"</td> <td class=\\\"text-center p-2\\\">\" + \r\n");
      out.write("\t\t\t\t\"<button class=\\\"btn btn-primary btn-floating\\\" title=\\\"Excluir Usuário\\\" id=\\\"excluir\\\" value=\\\"\"+ids[i]+\"\\\" style=\\\"background-color: #FF8A80\\\" type=\\\"button\\\" > \" + \r\n");
      out.write("\t\t\t\t\"<i class=\\\"fas fa-times\\\"></i> \" + \r\n");
      out.write("\t\t\t\t\"</button> </td>\";\r\n");
      out.write("\t\t\t\tsaida += \"</tr>\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#userList\").append(saida);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.getJSON(\"../Models/createRequestList.jsp\", {idUser: ");
      out.print(userId );
      out.write("}, function(data, status) {\r\n");
      out.write("\t\t\tvar saida = \"\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar RQids = data.RQid;\r\n");
      out.write("\t\t\tvar USids = data.USid;\r\n");
      out.write("\t\t\tvar nomes = data.nome;\r\n");
      out.write("\t\t\tvar niveisAt = data.nivelAt;\r\n");
      out.write("\t\t\tvar niveisAl = data.nivelAl;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfor(var i = 0; i < USids.length; i++){\r\n");
      out.write("\t\t\t\tsaida += \"<tr>\";\r\n");
      out.write("\t\t\t\tsaida += \"<td class=\\\"p-2\\\">\" + (i+1) + \r\n");
      out.write("\t\t\t\t\"</td> <td class=\\\"p-2\\\">\" + USids[i] + \r\n");
      out.write("\t\t\t\t\"</td> <td class=\\\"p-2\\\">\" + nomes[i] + \r\n");
      out.write("\t\t\t\t\"</td> <td class=\\\"p-2\\\">\" + niveisAt[i] +\r\n");
      out.write("\t\t\t\t\"</td> <td class=\\\"p-2\\\">\" + niveisAl[i] +\r\n");
      out.write("\t\t\t\t\"</td> <td class=\\\"text-center p-2\\\">\" +\r\n");
      out.write("\t\t\t\t\"<button class=\\\"btn btn-primary btn-floating\\\" title=\\\"Aceitar\\\" id=\\\"aceitar\\\" value=\\\"\"+RQids[i]+\"\\\" style=\\\"background-color: #00B74A\\\" type=\\\"button\\\" > \" + \r\n");
      out.write("\t\t\t\t\"<i class=\\\"fas fa-check\\\"></i> \" + \r\n");
      out.write("\t\t\t\t\"</button>\" +\r\n");
      out.write("\t\t\t\t\"<button class=\\\"btn btn-primary btn-floating\\\" title=\\\"Recusar\\\" id=\\\"recusar\\\" value=\\\"\"+RQids[i]+\"\\\" style=\\\"background-color: #FF8A80\\\" type=\\\"button\\\" > \" + \r\n");
      out.write("\t\t\t\t\"<i class=\\\"fas fa-times\\\"></i> \" + \r\n");
      out.write("\t\t\t\t\"</button> </td>\";\r\n");
      out.write("\t\t\t\tsaida += \"</tr>\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#requestList\").append(saida);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("\t\t");
}
   }
} 
      out.write("\r\n");
      out.write("\t   \r\n");
      out.write("\t\n");
      out.write("\t</body>\n");
      out.write("\t<script type=\"text/javascript\" src=\"../MDB/js/mdb.min.js\"></script>\t\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
